### ISSUE TITLE
文件的fileId是咋拿到的呢？

### ISSUE THREAD

**Issue by cnscorpions** [libsgh/PanIndex#10]
纯好奇😆

**Comment by libsgh** [comment]
![image](https://user-images.githubusercontent.com/25656088/101113644-cc536880-361a-11eb-9a94-4214cf716ba9.png)
当你点某个目录或查看某个文件时时，浏览器里面的地址栏最后面的就是文fileId

**Comment by cnscorpions** [comment]
thank you, 我看下哈
