### ISSUE TITLE
加密目录下子目录内文件可被搜索(不知道算不算个问题)

### ISSUE THREAD

**Issue by Cicini** [libsgh/PanIndex#101]
例:
加密`/a`，但`/a/b`下的文件依然可以被搜索到.
大概可以手动加密但子目录一多也确实麻烦(尤其是后台的目录加密设置目前是单行的，一多密码和目录ID混在一起属实麻烦)

**Comment by libsgh** [comment]
1. 是否更新了最新版v2.0.5
2. 是否更新后文件做了重新缓存

**Comment by Cicini** [comment]
> 1. 是否更新了最新版v2.0.5
> 2. 是否更新后文件做了重新缓存
>    最新版搜索已经最加密文件夹及下面的子文件做了隐藏处理

重新缓存一次文件后无法被搜索

**Comment by Cicini** [comment]
> 1. 是否更新了最新版v2.0.5
> 2. 是否更新后文件做了重新缓存
>    最新版搜索已经最加密文件夹及下面的子文件做了隐藏处理

以及2.0.4更新到2.0.5后
若本地浏览器的缓存未清除
加密文件夹无法确认密码输入
清除本地缓存后可解决
可以考虑写入release页面提醒需要清除本地缓存
