### ISSUE TITLE
建议增加对世纪互联的支持

### ISSUE THREAD

**Issue by ifvv** [libsgh/PanIndex#102]
世纪互联是国内版OneDrive
和国际版就API请求地址不一样，官方文档：
[https://docs.microsoft.com/zh-cn/previous-versions/office/office-365-api/api/o365-china-endpoints](https://docs.microsoft.com/zh-cn/previous-versions/office/office-365-api/api/o365-china-endpoints
)
希望作者能够增加对世纪互联的支持

**Comment by libsgh** [comment]
v2.0.8已添加对世纪互联的支持
