### ISSUE TITLE
进程启动异常

### ISSUE THREAD

**Issue by yuanzhidao** [libsgh/PanIndex#105]
![image](https://user-images.githubusercontent.com/37867590/131250552-db899206-891e-4cb1-ab5d-6a405d2681da.png)
![image](https://user-images.githubusercontent.com/37867590/131250560-74f3488d-e417-4611-bb9f-7a293e762947.png)
![image](https://user-images.githubusercontent.com/37867590/131250566-7bc3aac9-73fb-4e93-99cd-8d1177586c09.png)

**Comment by libsgh** [comment]
检查一下端口是否被占用了...
