### ISSUE TITLE
onedrive上传一直在转圈圈

### ISSUE THREAD

**Issue by Mabisi** [libsgh/PanIndex#111]
![image](https://user-images.githubusercontent.com/19968269/132405505-fbfcf872-1afc-4570-b7a9-0c5f2d7e4cff.png)

已经上传完成了，不走流量了还是在转 ，，把我服务器都卡死了

**Comment by libsgh** [comment]
不要上传太大的文件

**Comment by Mabisi** [comment]
> 不要上传太大的文件

200MB的 也大嘛。。好吧
