### ISSUE TITLE
预览时候出现ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by mxsix112** [libsgh/PanIndex#114]
![image](https://user-images.githubusercontent.com/42610747/132829359-2885815f-2091-4842-9933-6ae9cee147c5.png)
下载是正常的。不知道是什么原因

**Comment by libsgh** [comment]
请提供下日志

**Comment by mxsix112** [comment]
> 请提供下日志

2021/09/17 21:43:35 http: panic serving 172.18.0.1:41320: html/template: "pan/mdui-light/view-video.html" is undefined
这个模板的问题换了mdui就好了
