### ISSUE TITLE
求宝塔教程

### ISSUE THREAD

**Issue by arleycn** [libsgh/PanIndex#118]
比OLAINDEX好看方便，安装太难了

**Comment by NiTian1207** [comment]
@arleycn docker安装很简单的

**Comment by NiTian1207** [comment]
> 比OLAINDEX好看方便，安装太难了

我写了一个简易教程 https://www.nite07.com/panindex/ 可以参考一下

**Comment by arleycn** [comment]
感谢以上朋友解答
