### ISSUE TITLE
希望增加设置默认排序

### ISSUE THREAD

**Issue by NiTian1207** [libsgh/PanIndex#119]
我又来提issue了，libsgh不要打我 😂
阿里盘默认排序是上传时间，od默认是文件名，强迫症看着有点难受

**Comment by libsgh** [comment]
v2.0.5版本已经加了排序，可以指定按照时间大小名称排序，而且会以cookie的方式记住排序选择

**Comment by NiTian1207** [comment]
> v2.0.5版本已经加了排序，可以指定按照时间大小名称排序，而且会以cookie的方式记住排序选择

如果没有cookie,阿里盘默认的排序是上传时间,我的意思是修改这个默认按上传时间排序

**Comment by libsgh** [comment]
那就选择默认排序

> > v2.0.5版本已经加了排序，可以指定按照时间大小名称排序，而且会以cookie的方式记住排序选择
> 
> 如果没有cookie,阿里盘默认的排序是上传时间,我的意思是修改这个默认按上传时间排序

默认排序就是网盘的默认排序，PanIndex没有做处理的

**Comment by NiTian1207** [comment]
> 那就选择默认排序
> 
> > > v2.0.5版本已经加了排序，可以指定按照时间大小名称排序，而且会以cookie的方式记住排序选择
> > 
> > 
> > 如果没有cookie,阿里盘默认的排序是上传时间,我的意思是修改这个默认按上传时间排序
> 
> 默认排序就是网盘的默认排序，PanIndex没有做处理的

我就是想在后台设置中指定默认排序方式 😂

**Comment by libsgh** [comment]
> > 那就选择默认排序
> > > > v2.0.5版本已经加了排序，可以指定按照时间大小名称排序，而且会以cookie的方式记住排序选择
> > > 
> > > 
> > > 如果没有cookie,阿里盘默认的排序是上传时间,我的意思是修改这个默认按上传时间排序
> > 
> > 
> > 默认排序就是网盘的默认排序，PanIndex没有做处理的
> 
> 我就是想在后台设置中指定默认排序方式 😂

感觉用处不太大，后面看需求吧

**Comment by NiTian1207** [comment]
> > > 那就选择默认排序
> > > > > v2.0.5版本已经加了排序，可以指定按照时间大小名称排序，而且会以cookie的方式记住排序选择
> > > > 
> > > > 
> > > > 如果没有cookie,阿里盘默认的排序是上传时间,我的意思是修改这个默认按上传时间排序
> > > 
> > > 
> > > 默认排序就是网盘的默认排序，PanIndex没有做处理的
> > 
> > 
> > 我就是想在后台设置中指定默认排序方式 😂
> 
> 感觉用处不太大，后面看需求吧

好的
