### ISSUE TITLE
较多文件的网盘刷新缓存耗时显著提升（Onedrive）

### ISSUE THREAD

**Issue by ljm12914** [libsgh/PanIndex#120]
如题，当我刷新存有1000个文件的网盘的缓存时，我需要等待一分钟左右，并且我作出的改动仅仅是增加了一个文件，或者什么都没做。是否可以在这种场景下适当压缩刷新时间？

我的服务器架设在国外，带宽足够，并与我作为网盘的Onedrive账户的主数据中心在同一地区。

P.S.：为什么我会认为这个耗时较长？因为Oneindex刷新同样规模的缓存（准确地说是同一个Onedrive账户）仅花费了8-10s。

**Comment by ljm12914** [comment]
我写了一个Onedrive安装教程：https://blog.csdn.net/LJM12914/article/details/120393394 ，看到我的吐槽不要打我😂

**Comment by libsgh** [comment]
1. 刷新缓存是刷新全部文件，手动刷新的时候可以指定刷新的目录，这样可以提升效率
2. 缓存速度取决于你的服务器调用onedrive api的速度、以及硬盘写入速度（数据库基于sqlite）
3. 每遇到文件夹会调用一次接口，所以文件夹的数量也会直接影响缓存时间

**Comment by ljm12914** [comment]
soga
还有一个小问题，两个冒号
![屏幕截图 2021-09-21 110330](https://user-images.githubusercontent.com/29831474/134105472-03fb044a-68ea-43e3-8517-2d2c5f9daf78.png)
