### ISSUE TITLE
增加 SFTP 网盘支持？

### ISSUE THREAD

**Issue by kasuganosoras** [libsgh/PanIndex#124]
如果可以通过 SFTP 将局域网其他 Linux 主机的目录共享出来貌似也是不错的功能。

应用场景：我的局域网内有多台 Linux 主机，平时如果需要访问这些主机上的文件需要通过 SFTP，或者在每台主机上部署 Nginx，在主机数量多的时候会比较麻烦，如果有这么个功能可以把每台主机的 SFTP 整合到一个网页上，然后提供匿名访问下载的功能，应该是不错的。

**Comment by libsgh** [comment]
好想法！不过最近没时间搞

**Comment by libsgh** [comment]
增加了FTP
