### ISSUE TITLE
不知道是什么问题

### ISSUE THREAD

**Issue by Shang-SRant** [libsgh/PanIndex#125]
更新了token，还是一样的。
![image](https://user-images.githubusercontent.com/59569323/134591754-4728ec04-d718-4bcb-8fe6-33414403065a.png)

**Comment by Shang-SRant** [comment]
刚试了一下，可以缓存目录，但是不管是视频还是文档，均下载不了，也不能在线看

**Comment by libsgh** [comment]
请获取手机端的token，具体方法，看下文档，或是自行百度

**Comment by Shang-SRant** [comment]
好的，谢谢！
