### ISSUE TITLE
天翼云盘缓存问题

### ISSUE THREAD

**Issue by 5sir** [libsgh/PanIndex#126]
使用v2.0.6版本 定时刷新后缓存的文件不全 只剩下一个文件夹了 环境为Heroku

**Comment by libsgh** [comment]
能提供下日志吗

**Comment by 5sir** [comment]
日志里面提示的是缓存刷新成功  但是一自动刷新 文件就不全了 就只剩下一个文件夹了
[目录缓存][Cloud189]缓存刷新 >> 刷新成功

**Comment by libsgh** [comment]
重新部署安装一下，版本没有更新
