### ISSUE TITLE
阿里云网盘部署

### ISSUE THREAD

**Issue by doubi666** [libsgh/PanIndex#127]
{
  "host": "0.0.0.0",
  "port": 8080,
  "accounts": [
    {
      "id": "fbfd8891-f9ed-4889-9ae4-6c2cb0e51b43",
      "name": "Index of",
      "mode": "native",
      "user": "",
      "password": "",
      "refresh_token": "",
      "access_token": "",
      "root_id": "/opt/share",
      "default": 1,
      "files_count": 0,
      "status": 3,
      "time_span": "0s",
      "last_op_time": "2021-05-07 17:46:53"
    },
    {
      "id": "b0d8774e-9cdc-4b3a-b6fa-1bdfb5ecdd2e",
      "name": "teambition项目盘",
      "mode": "teambition",
      "user": "182********",
      "password": "******",
      "refresh_token": "",
      "access_token": "",
      "root_id": "6049bbea997fc9a15fc38b3f",
      "default": 0,
      "files_count": 13,
      "status": 2,
      "time_span": "7.8s",
      "last_op_time": "2021-05-07 17:47:03"
    }
  ],
  "pwd_dir_id": "/opt/share:1234,5149631198973335:1234",
  "hide_file_id": "234vsdr2342,/opt/share/hide",
  "heroku_app_url": "",
  "api_token": "1234",
  "theme": "mdui",
  "admin_password": "1234",
  "damagou": {
    "username": "",
    "password": ""
  },
  "only_referrer": "baidu.com,google.com",
  "refresh_cookie": "0 0 8 1/1 * ?",
  "update_folder_cache": "",
  "heroku_keep_alive": "",
  "footer": ""
}   

配置文件修改哪几项？  问下是全部复制进去还是复制某段就可以了

**Comment by Cicini** [comment]
看文档，现在已经不在文件里修改了，去后台改

**Comment by doubi666** [comment]
> 看文档，现在已经不在文件里修改了，去后台改

现在是到heroku部署页面直接点击Deploy app完成部署 就可以了么 然后去后台？   我看在线文档没修改过  还是从config里面复制...

**Comment by Cicini** [comment]
https://libsgh.github.io/PanIndex/#/config

**Comment by libsgh** [comment]
如果是从后台那里获取的，直接复制就好
