### ISSUE TITLE
希望可以支持挂载Google Drive

### ISSUE THREAD

**Issue by Youwenqwq** [libsgh/PanIndex#128]
希望可以支持挂载Google Drive。

之前用Google Drive挂载，一直都只用CloudFlare Worker搭建网页，不能整合到一个程序里，管理起来比较麻烦😭，虽然直接挂载可能导致国内无法访问，但是我之前看到Sharelist列表程序(因为Bug和速度慢不用了)的处理办法还比较方便，就是利用中转服务器，用列表程序列表，用CloudFlare Worker中转下载流量，这样就可以实现又能列表又能在国内正常下载了，还可以直接在列表程序里管理，感觉真不戳

因此希望PanIndex也能制作出相关功能qwq

附：
上文提到的Sharelist部署在Cloudflare Worker上的脚本：
[cf-worker.js](https://github.com/reruin/sharelist/blob/0.1/proxy/cf-worker.js)
[Sharelist程序](https://github.com/reruin/sharelist/tree/0.1)

**Comment by libsgh** [comment]
后面会逐步添加更多网盘的支持，近期的目标是完善功能和提高稳定性

**Comment by Youwenqwq** [comment]
已实现
