### ISSUE TITLE
阿里云盘缓存问题

### ISSUE THREAD

**Issue by zouhy2001** [libsgh/PanIndex#129]
refresh_token 填写保存后,不是自己填写的token
另外有更方便的方法获取token
![image](https://user-images.githubusercontent.com/57806936/135738564-2b3a58a2-9dfa-4cb3-948a-a4bc1d0fd1fa.png)

**Comment by zouhy2001** [comment]
解决了,原来空文件夹也会无法获取缓存链

**Comment by libsgh** [comment]
1. 为避免token失效，保存后用你的refresh_token重新获取了新的token
2. 电脑端网页获取的token无法在PanIndex上使用，需要用手机端的token，否则会出现无法下载的问题

**Comment by zouhy2001** [comment]
> 1. 为避免token失效，保存后用你的refresh_token重新获取了新的token
> 2. 电脑端网页获取的token无法在PanIndex上使用，需要用手机端的token，否则会出现无法下载的问题

原来如此,多谢了,但如果是空文件夹,确实会报错获取失败

**Comment by zouhy2001** [comment]
感觉还不错,给个star👍

**Comment by libsgh** [comment]
> > 1. 为避免token失效，保存后用你的refresh_token重新获取了新的token
> > 2. 电脑端网页获取的token无法在PanIndex上使用，需要用手机端的token，否则会出现无法下载的问题
> 
> 原来如此,多谢了,但如果是空文件夹,确实会报错获取失败

提供下版本号和错误日志，我这里测试空文件夹可以缓存的。

**Comment by zouhy2001** [comment]
> > > 1. 为避免token失效，保存后用你的refresh_token重新获取了新的token
> > > 2. 电脑端网页获取的token无法在PanIndex上使用，需要用手机端的token，否则会出现无法下载的问题
> > 
> > 
> > 原来如此,多谢了,但如果是空文件夹,确实会报错获取失败
> 
> 提供下版本号和错误日志，我这里测试空文件夹可以缓存的。

2.06 日志输出没有看到error 但使用的时候我一直以为自己哪里配置错了,我这能够问题复现.
![image](https://user-images.githubusercontent.com/57806936/135739140-b7c37820-679a-4fa4-b549-b276731b42b3.png)

![image](https://user-images.githubusercontent.com/57806936/135739131-95562338-147f-4251-8578-fa4680fbb10f.png)

![image](https://user-images.githubusercontent.com/57806936/135739152-342047ab-c8b5-48fd-96cf-1fbe0fb66073.png)

![image](https://user-images.githubusercontent.com/57806936/135739161-bcd31a25-fd45-4fa7-bb49-066fd5318724.png)
