### ISSUE TITLE
[bug]文件夹问题

### ISSUE THREAD

**Issue by LuoMuyu** [libsgh/PanIndex#13]
当文件夹名中有类似于_之类的字符时会导致404错误

**Comment by libsgh** [comment]
测试`_`是可以的，请发下你的完整目录名称，而且天翼云网盘创建目录的时候有些特殊字符的文件夹本身就禁止创建

**Comment by LuoMuyu** [comment]
希薇娅Civia_images

**Comment by LuoMuyu** [comment]
在下载里面文件的时候会404

**Comment by LuoMuyu** [comment]
删掉data重新生成就好了，可能是缓存的问题。。。

**Comment by libsgh** [comment]
> 删掉data重新生成就好了，可能是缓存的问题。。。

目录缓存是一小时，可以调用接口手动清理，也可以重启应用。不用删掉data目录。
