### ISSUE TITLE
天翼网盘缓存失败

### ISSUE THREAD

**Issue by sw586** [libsgh/PanIndex#131]
缓存记录
cookie： 正常

状态： 缓存失败

文件数：-

耗时：1.1s

最近一次缓存：2021-10-08 18:38:05

刷新cookie 刷新缓存

**Comment by sw586** [comment]
>情况：
> 
> 1. 缓存的文件夹内有文件
> 2. 根目录id设置无误
> 3. herokuapp环境
4、阿里云盘正常

**Comment by libsgh** [comment]
> > > > 情况：
> > > > 
> > > > 1. 选中的文件夹内有文件
> > > > 2. 根目录id设置无误
> > > > 3. herokuapp环境
> > > >    4、阿里云盘正常
> > 
> > 
> > 有可能你的版本还是2.0.5，如果是fork项目，通过github仓库部署，可以重启更新，如果是直接通过链接部署的，必须重装下，指定版本更新的还不能用
> 
> 不是fork项目，是今天通过本项目介绍页面的herokuapp方式安装的

重新安装一下
