### ISSUE TITLE
使用问题、配置问题可以在进 Discussions 讨论

### ISSUE THREAD

**Issue by libsgh** [libsgh/PanIndex#133]
开通了 Discussions，关于使用问题、配置问题建议到 [Discussions](https://github.com/libsgh/PanIndex/discussions) 讨论，方便交流。

**Comment by nitezs** [comment]
😄

**Comment by ddkwork** [comment]
这是离线下载vs2022，sdk ,wdk,,ewdk, 系统iso，skia等等这些大东西的大杀器啊，哈哈
