### ISSUE TITLE
恳请支持自定义HTML&css等

### ISSUE THREAD

**Issue by y377** [libsgh/PanIndex#15]
首先程序很棒，我很喜欢！

- 因为不会go,所以我无法自定义HTML以及CSS，主程序是一个二进制文件
- 下图HTML在PC浏览器底部的_Powered by_显得过高，手机界面同样如此；影响整体美观；
- 我想用大陆备号域名这样可增加访问流畅性，因为主程序我不知如何更改
- 期待出一个可自定义的版本，谢谢！

![image](https://user-images.githubusercontent.com/58632405/105533536-3a690180-5d27-11eb-9a70-a70f7024f33e.png)
![image](https://user-images.githubusercontent.com/58632405/105533689-70a68100-5d27-11eb-97a6-e7f38a4289de.png)
[我自己的测试demo](https://www.hupan.vip)

**Comment by libsgh** [comment]
你可以直接下载源码，按需修改后启动，页面在`templates`下
- 安装git和golang
- 设置go环境变量`go env -w GO111MODULE=on`
- 如果是国内服务器，设置下代理`go env -w GOPROXY=https://goproxy.cn,direct`
- 从源码直接运行
```
$ git clone https://github.com/libsgh/PanIndex.git
$ cd PanIndex
$ go run main.go -config config/config.json
```
- 也可以下载源码后自行编译成二进制程序再执行
以linux,amd64为例
```
$ CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o PanIndex
$ nohup ./PanIndex -config config/config.json &
```
