### ISSUE TITLE
HEAD.md渲染bug

### ISSUE THREAD

**Issue by ljm12914** [libsgh/PanIndex#153]
`HEAD.md`不自动渲染，必须在外观——自定义JS处加上`<script>document.getElementById("headContent").style.display="block"</script>`才能显示。
然后如果更新了`HEAD.md`文件，无论怎么改配置改缓存都无法更新被展示出来的`HEAD.md`缓存，**必须重启程序才能更新**。

**Comment by libsgh** [comment]
v2.0.8已解决
