### ISSUE TITLE
多网盘挂载只有第一个网盘的目录密码有效，建议增加网站密码

### ISSUE THREAD

**Issue by zyjia** [libsgh/PanIndex#155]
我挂了3个网盘，分别是本地/天翼根目录/阿里云盘根目录，设置了目录密码访问，只有本地的网盘进入需要密码，其它都是直接进去，另外建议增加网站密码，这样不设置目录密码更方便。
我的设置如下：
密码文件（夹）
/volume1/web:XXXXXX,-11:XXXXXX,root:XXXXXX

**Comment by libsgh** [comment]
正在优化密码访问，目前的版本不支持在根目录设置密码

**Comment by libsgh** [comment]
v2.0.8版本已经做了优化
