### ISSUE TITLE
Docker启动报错

### ISSUE THREAD

**Issue by li-xunhuan** [libsgh/PanIndex#16]
启动命令：  
> `docker run -itd --name PanIndex -d -p 1280:8080 -e CLOUD_USER="账号" -e CLOUD_PASSWORD="密码" -e ROOT_ID="不看" -e API_TOKEN="Kl3JNCN5vi3l2mtN" -e THEME="materialdesign" iicm/pan-index`
运行结果： 
![20210124085750](https://user-images.githubusercontent.com/10476982/105618456-569d9900-5e22-11eb-9bd0-f98d01113b16.jpg)

**Comment by libsgh** [comment]
使用最新docker镜像再试试，启动命令有修改`./PanIndex -config config.json`

**Comment by li-xunhuan** [comment]
还是那样的，依然报错
```
2021/01/25 23:54:09 [程序启动]Sqlite数据库 >> 连接成功
flag provided but not defined: -config /app/config.json
Usage of /app/PanIndex:
  -config string
    	配置文件config.json的路径 (default "config.json")
root@Tello:/mnt/sdb1/data/pan_index# ls
config.json

```

**Comment by libsgh** [comment]
> 还是那样的，依然报错
> 
> ```
> 2021/01/25 23:54:09 [程序启动]Sqlite数据库 >> 连接成功
> flag provided but not defined: -config /app/config.json
> Usage of /app/PanIndex:
>   -config string
>     	配置文件config.json的路径 (default "config.json")
> root@Tello:/mnt/sdb1/data/pan_index# ls
> config.json
> ```

抱歉，启动命令问题，已经修改并测试，再重新试试。

**Comment by li-xunhuan** [comment]
稳妥，跑起来了，话说，几个不同的主题都长啥样啊？

**Comment by libsgh** [comment]
![截图录屏_选择区域_20210126135137](https://user-images.githubusercontent.com/25656088/105805924-f3f0fc80-5fdd-11eb-9373-738c8062158a.png)
![截图录屏_选择区域_20210126135243](https://user-images.githubusercontent.com/25656088/105805932-f5bac000-5fdd-11eb-9001-d9aa94f7d948.png)

这两个主题比较类似，后面会添加一个更好看一点的主题，手机也能很友好展示的

**Comment by li-xunhuan** [comment]
nice，老哥牛逼！
