### ISSUE TITLE
heroku安装不了

### ISSUE THREAD

**Issue by sw586** [libsgh/PanIndex#163]
![QQ截图20211106145438](https://user-images.githubusercontent.com/24788222/140600971-76d15f74-a26c-4b8d-8eb3-40040d4a70ba.png)
![QQ截图20211106145448](https://user-images.githubusercontent.com/24788222/140600972-6dc6dbdf-7fbf-499b-937a-b673a264f7ff.png)

**Comment by libsgh** [comment]
v2.0.8已解决

**Comment by sw586** [comment]
> v2.0.8已解决

辛苦了
