### ISSUE TITLE
ts格式无法播放

### ISSUE THREAD

**Issue by sw586** [libsgh/PanIndex#164]
链接在PC播放器上也播放不出来

**Comment by libsgh** [comment]
能不能给个链接

**Comment by sw586** [comment]
> 不能给个链接

可以不要走开

**Comment by sw586** [comment]
> 不能给个链接

http://test12345.52jsm.com/d_0/vide/%e4%b8%89%e5%9b%bd%e6%bc%94%e4%b9%89/%e7%ac%ac27%e9%9b%86%20%e4%b8%89%e9%a1%be%e8%8c%85%e5%ba%90.ts?v

**Comment by libsgh** [comment]
貌似ts文件不是h5播放器支持的视频格式，下版本会把默认格式中的ts文件去掉，请转码成其他格式播放。

**Comment by sw586** [comment]
> 貌似ts文件不是h5播放器支持的视频格式，下版本会把默认格式中的ts文件去掉，请转码成其他格式播放。

辛苦了，希望保留下载，期盼加入支持和彩云，你最棒了！
