### ISSUE TITLE
Onedrive登录正常，却一直缓存中

### ISSUE THREAD

**Issue by yefenghu** [libsgh/PanIndex#165]
我是在黑裙上安装的PanIndex，登录的Onedrive for Buiess，登录账户后，一在缓存中没有任何文件出现，其他天翼云和本地正常
![image](https://user-images.githubusercontent.com/81460075/140628890-f643252c-82e5-42c6-9615-d6ca6172e9b0.png)
![image](https://user-images.githubusercontent.com/81460075/140628901-6dcc344f-bf6e-4825-8518-cd93e7e9e345.png)
上图中这个网盘模式每次重新进入时都会自动变为本地磁盘。。。
![image](https://user-images.githubusercontent.com/81460075/140628909-0f88d8e0-c9b3-40bd-98cc-cb6213d0382c.png)

**Comment by libsgh** [comment]
只是显示问题，网盘的真实类型没问题。如果文件很多，缓存需要时间，也有可能中间有错误。可以尝试重新保存挂载盘，会重新缓存。

**Comment by yqnnko** [comment]
我缓存多文件大概是这个速度
![image](https://user-images.githubusercontent.com/84311024/140630308-8eb9fcbb-416b-4af0-a414-5e5aa64843d6.png)

**Comment by yefenghu** [comment]
> 我查看了多文件大概是这个速度 ![图片](https://user-images.githubusercontent.com/84311024/140630308-8eb9fcbb-416b-4af0-a414-5e5aa64843d6.png)

我已经缓存了一个晚上了，还是一个文件没有

**Comment by yefenghu** [comment]
> 只是显示问题，网盘的真实类型没问题。如果文件过多，需要时间，也有可能中间有错误。

不只是显示问题，实际上也没有文件。我缓存了一个晚上，还是没有任何文件。怎么看看有错误？

**Comment by libsgh** [comment]
查看日志，和数据库文件 看下文件表里面是不是有数据状态是不是正常的，sqlite，没有测试过这么大量的缓存

**Comment by yefenghu** [comment]
> 查看日志，和数据库文件看下文件表里面是不是有数据状态是正常的，sqlite，没有测试过这么大量的缓存

尴尬的是，不知道如何查看指定群辉套件的日志，我这边只能看群辉的日志。。。。。而且我的数据库是Mysql

**Comment by yefenghu** [comment]
> > 查看日志，和数据库文件看下表里面是不是有数据状态是正常的，sqlite，没有测试过这么大量的文件
> 
> 尴尬的是，不知道如何查看指定群辉套件的日志，我这个只能看群辉的。。。。。而且我的数据库是Mysql

![image](https://user-images.githubusercontent.com/81460075/140633889-da345f76-33b2-477c-8a44-1be2f73cc0d8.png)
我就看了下群辉的日志，现在可以看到缓存文件了，不过这个效率。。。。

**Comment by libsgh** [comment]
> > > 查看日志，和数据库文件看下表里面是不是有数据状态是正常的，sqlite，没有测试过这么大量的文件
> > 
> > 
> > 尴尬的是，不知道如何查看指定群辉套件的日志，我这个只能看群辉的。。。。。而且我的数据库是Mysql
> 
> ![image](https://user-images.githubusercontent.com/81460075/140633889-da345f76-33b2-477c-8a44-1be2f73cc0d8.png) 我就看了下群辉的日志，现在可以看到缓存文件了，不过这个效率。。。。

1. 数据库用的sqlite不是mysql
2. 同步时间长可能是api调用受到了限制，你的文件太多了...
3. 只有29个文件可能是大部分文件都缓存失败了，猜测是接口访问问题，具体要拿到完整日志 或是测试
