### ISSUE TITLE
希望增加渲染 Readme.md，渲染在文件列表之后

### ISSUE THREAD

**Issue by yqnnko** [libsgh/PanIndex#166]
希望增加渲染 Readme.md，渲染在文件列表之后

同样遇到了HEAD.md无法显示的问题，另外建议忽略这俩单词的大小写

**Comment by yqnnko** [comment]
看了看聊天记录，搞糊涂了，现在到底支持README.me 的渲染吗，刚刚传了个文件试了下好像没有？

**Comment by libsgh** [comment]
支持的，不过渲染的js更新导致渲染报错，导致无法显示，208版本会修复

**Comment by libsgh** [comment]
v2.0.8已解决
