### ISSUE TITLE
最新的文件夹排在了最底下，而不是最前面

### ISSUE THREAD

**Issue by li-xunhuan** [libsgh/PanIndex#17]
<img width="1301" alt="QQ20210128-203010@2x" src="https://user-images.githubusercontent.com/10476982/106138926-bb9d1a00-61a7-11eb-96d7-e64e13a39f09.png">

**Comment by libsgh** [comment]
能否贴一下你在天翼云网盘还需的图片

**Comment by li-xunhuan** [comment]
> 它是这样的，按顺序排列的
![123](https://user-images.githubusercontent.com/10476982/106224176-cf836300-621d-11eb-8d6a-bfeadd968100.png)

**Comment by libsgh** [comment]
下个版本会加个序号进行精确排序

**Comment by y377** [comment]
我还是觉得按首字母ABCD...排列比较好，可能众口难调，这对作者是一大“考验”

**Comment by libsgh** [comment]
> 我还是觉得按首字母ABCD...排列比较好，可能众口难调，这对作者是一大“考验”

天翼云里面什么顺序，PanIndex保持一致就行了

**Comment by libsgh** [comment]
v1.0.3解决了排序问题
