### ISSUE TITLE
大佬2.8你太厉害了

### ISSUE THREAD

**Issue by sw586** [libsgh/PanIndex#179]
非常感谢您提供这么好的开源软件，常用网盘基本全了太厉害了！不久相信会有更多人使用PanIndex！太香了。

视频播放问题是我反馈的，没想到您老直接干上转码功能，实在是太强了！！

最后想探讨点PanIndex部署herokuku的使用技巧：
1、您认为herokuku最佳的加速方案是什么？

A、自选IP==》workers==>herokuku                        
B、===》自选IP+华为云+萌精灵DNS==>herokuku
C、请补充

2、使用herokuku绑定信用卡，确定不会产生费用吗，万一产生流量？

**Comment by libsgh** [comment]
感谢支持，PanIndex还有不少问题，会慢慢优化
1. 我只套过cf，heroku的问题主要是访问国内网盘api比较慢，导致缓存慢，访问其实还好，还有就是主要依赖于sqlite数据库，heroku的沙盒环境不太合适
2. heroku绑卡后只要你用free plan也不会产生费用，不是按照流量计费

**Comment by sw586** [comment]
> 感谢支持，PanIndex还有不少问题，会慢慢优化
> 
> 1. 我只套过cf，heroku的问题主要是访问国内网盘api比较慢，导致缓存慢，访问其实还好，还有就是主要依赖于sqlite数据库，heroku的沙盒环境不太合适
> 2. heroku绑卡后只要你用free plan也不会产生费用，不是按照流量计费

好的 感谢回复！
