### ISSUE TITLE
请问各个目录的root_id怎么看

### ISSUE THREAD

**Issue by pizixi** [libsgh/PanIndex#18]
因为不想直接把根目录下所有文件暴露在公网上，只想暴露一个子文件夹该怎么找root_id，另外加上搜索功能还有单文件或文件夹分享链接就更好了，感谢作者

**Comment by libsgh** [comment]
1. 登录你的天翼云网盘：https://cloud.189.cn/main.action
2. 打开你要作为分享的根目录，浏览器的地址会变成https://cloud.189.cn/main.action#home/folder/41301310689345676
3. `41301310689345676`就是目录id
4. 最上层的目录id为`-11`
