### ISSUE TITLE
发现使用herokuku会回档？

### ISSUE THREAD

**Issue by sw586** [libsgh/PanIndex#182]
使用herokuku
昨天：
1、安装PanIndex，配置文件有3个网盘
2、添加了1个网盘，总共4个
3、修改密码
4、关机睡觉

今天：
1、密码恢复为修改前默认的
2、网盘退回安装时填写的3盘配置，只有 3个网盘了
3、网盘文件为空

herokuku是已经绑定信用卡的，好奇怪

**Comment by libsgh** [comment]
heroku本身就是沙盘环境，临时文件会被清空，配置还好办可以放到环境变量，但是缓存的目录信息还是会丢，有雨PanIndex用了文件数据库sqlite，所以目前不太适合这个环境了。
