### ISSUE TITLE
请问定时任务怎么操作呢。

### ISSUE THREAD

**Issue by hkthomas** [libsgh/PanIndex#188]
0 0 6,18 * * ? *
0 0 6/18 * * ? *
0 0 2 * * ? *

从网页上生成的，可是全都不运行，缓存时间一直是上次手动缓存的时间，应该怎么操作鸭。

**Comment by libsgh** [comment]
如果是用生成器生成我这里是这样的`0 0 8,16 * * ?`，你可以试试
在线生成：https://cron.qqe2.com/

**Comment by hkthomas** [comment]
> 如果是用生成器生成我这里是这样的`0 0 8,16 * * ?`，你可以试试 在线生成：https://cron.qqe2.com/

谢谢，我试一下。

**Comment by hkthomas** [comment]
[https://z3.ax1x.com/2021/11/24/oCNKmj.png](url)
老哥，我按照你给的添加进去，我设置了第一个跟第三个。

刚刚我上去看了下，第三个我没有设置但是执行了。。。。第一个却没有。

**Comment by hkthomas** [comment]
![image][(https://github.com/panacena/mengqu/blob/master/readme/Screenshot_2016-07-10-22-17- 15_zkk.com.mengqu.png](https://z3.ax1x.com/2021/11/24/oCNKmj.png))

**Comment by hkthomas** [comment]
![](https://z3.ax1x.com/2021/11/24/oCNKmj.png)

**Comment by tonyzhou777** [comment]
我这里用生成器生成的定时任务，也不执行。

**Comment by NoverNobida** [comment]
这个定时任务执行完全是混乱的。有添加了的从来不执行的，有添加了执行时间完全不对的，有没有添加但反而执行的。

**Comment by libsgh** [comment]
更新下新版试试
