### ISSUE TITLE
文件下载和文件预览都无效

### ISSUE THREAD

**Issue by algerkong** [libsgh/PanIndex#189]
使用的阿里云盘挂载
最新源码运行
![image](http://tvax4.sinaimg.cn/large/006opRgRgy1gwoy6p6s4aj30qi079jv7.jpg)

但是预览视频 文件什么的都不行
转码也没用
![image](http://tvax3.sinaimg.cn/large/006opRgRgy1gwoy61ylgdj30nj06caag.jpg)

下载报这个错
![image](http://tvax2.sinaimg.cn/large/006opRgRgy1gwoy30opsoj318x0fuk4h.jpg)

**Comment by libsgh** [comment]
用手机端的token，推荐用文档中的获取方式。电脑端的token会出现可以缓存，但是无法下载和预览的问题。
