### ISSUE TITLE
请问和彩云怎样配置呢

### ISSUE THREAD

**Issue by hyathlon** [libsgh/PanIndex#193]
请问和彩云怎样配置呢

**Comment by hyathlon** [comment]
登录状态长时间都是刷新中

**Comment by hkthomas** [comment]
登录网页版和彩云 - F12 - 获取cookie。

**Comment by hyathlon** [comment]
> 登录网页版和彩云 - F12 - 获取cookie。

就是这么弄的，但试了多次，都不得

**Comment by libsgh** [comment]
1. 登录网页版和彩云
2. F12打开开发者工具
3.  找到首页的那个请求`https://yun.139.com/w/`
4. 在右侧的request中找到Cookie并复制全部内容
5. 到PanIndex后台绑定

**Comment by caryyu** [comment]
建议考虑使用 chromedp 做一个模拟登录获取 Cookie 的功能。
