### ISSUE TITLE
大佬 有部分MP4视频会加载失败，部分正常，是什么原因导致

### ISSUE THREAD

**Issue by fjlu** [libsgh/PanIndex#194]

**Comment by 1462965833** [comment]
同问

**Comment by libsgh** [comment]
H5 video播放对下面的编码格式支持较好，其他格式可能会出现加载失败，黑屏等问题
MP4：
MPEG 4文件使用 H264 视频编解码器和AAC音频编解码器

WebM：
WebM 文件使用 VP8 视频编解码器和 Vorbis 音频编解码器

Ogg ：
Ogg 文件使用 Theora 视频编解码器和 Vorbis音频编解码器
