### ISSUE TITLE
文件名排序的问题

### ISSUE THREAD

**Issue by ywzhaiqi** [libsgh/PanIndex#198]
比如下面这个列表，目前按倒序排列是这样
```
"9.9.md", "9.7.md", "9.14.md", "11.9.md"
```
我希望的是这样排序
```
"11.9.md", "9.14.md","9.9.md", "9.7.md",
```

**Comment by hanqingwu** [comment]
我看了下代码，当前应该是用 字符串比较 '9'=0x39 比 '1' =0x31 大，则不是用数值9跟11 做比较， 你这个需求比较特殊。
需要判断字符串前半部分是否可以转为数值，如果可以转，则用数值比较。
不知道是否能适用所有场景。

**Comment by ywzhaiqi** [comment]
多谢。麻烦就算了。我手动更改文件名实现了自己的需求。

**Comment by hanqingwu** [comment]
周末看了相关的资料，这种排序法叫做 natural sort order ， 比简单的字符串比较更友好。

**Comment by hanqingwu** [comment]
测试了下，用 github.com/facette/natsort 可以比较好的实现 natural sort ， 
如果你需要的话，我可以提个request 上去。

**Comment by libsgh** [comment]
> 测试了下，用 github.com/facette/natsort 可以比较好的实现 natural sort ， 如果你需要的话，我可以提个request 上去。

目前使用的是数据库中的字段排序，如果对查出的列表再次排序会影响性能，具体如何还需要测试
这个不是那么紧急需要的吧...

**Comment by libsgh** [comment]
v3版本中，播放页面支持播放列表，是自然排序
