### ISSUE TITLE
webdav 视频无法快进

### ISSUE THREAD

**Issue by yx10010** [libsgh/PanIndex#199]
webdav挂载后视频无法快进跟拖动，阿里云盘视频加载失败，还有大佬能不能把播放器弄成可以视频列表显示，比如一个文件夹夹里面有10个视频，然后打开一个视频，播放列表可以显示文件夹里面的点击切换

**Comment by libsgh** [comment]
native、webdav现在还不支持断点，后面会强化这部分功能，播放列表可能要后排了，毕竟不是PanIndex的主要功能

**Comment by libsgh** [comment]
v3版本已实现
