### ISSUE TITLE
删除天翼云网盘里面的文件之后PanIndex里面的目录和文件都还在

### ISSUE THREAD

**Issue by pizixi** [libsgh/PanIndex#20]

**Comment by libsgh** [comment]
- PanIndex（程序启动、每一小时）同步天翼云的网盘数据，如果你在天翼云网盘对文件有任何操作，这里都不会立即刷新，要么等一小时自动刷新，如果想立即生效，手动调用下api接口刷新。
![image](https://user-images.githubusercontent.com/25656088/107166795-031a7600-69f2-11eb-9a9a-cbc2298c4371.png)
![image](https://user-images.githubusercontent.com/25656088/107166806-0c0b4780-69f2-11eb-8a30-deafebf33ce1.png)
![image](https://user-images.githubusercontent.com/25656088/107166815-13325580-69f2-11eb-87f6-37d22b25ff84.png)
- 你的上一个issue我已经非常清晰的回复你了，所以就随手**关闭**了，我什么时候删除你的issue了？看清楚再喷？软件bug多我没逼你用吧，我也没收费，觉得不好可以不用吧。

**Comment by pizixi** [comment]
> * PanIndex（程序启动、每一小时）同步天翼云的网盘数据，如果你在天翼云网盘对文件有任何操作，这里都不会立即刷新，要么等一小时自动刷新，如果想立即生效，手动调用下api接口刷新。
>   ![image](https://user-images.githubusercontent.com/25656088/107166795-031a7600-69f2-11eb-9a9a-cbc2298c4371.png)
>   ![image](https://user-images.githubusercontent.com/25656088/107167124-f8acac00-69f2-11eb-9434-e032e401ef36.png)
>   ![image](https://user-images.githubusercontent.com/25656088/107167084-dfa3fb00-69f2-11eb-827c-8e8d9f049b33.png)
> * 你的上一个issue我已经非常清晰的回复你了，所以就随手**关闭**了，我什么时候删除你的issue了？看清楚再喷？软件bug多我没逼你用吧，我也没收费，觉得不好可以不用吧。

* 我的问题，没看清楚，在此给你道歉。
