### ISSUE TITLE
下载文件夹报错

### ISSUE THREAD

**Issue by EchoGroot** [libsgh/PanIndex#207]
{
  "error": "MisdirectedRequest",
  "message": "The request was directed at a server that is not able to produce a response."
}

下载单个文件正常

**Comment by EchoGroot** [comment]
点击下载打开的页面地址：https://file.aliyundrive.com/files/archive?task_id=f05be9fa-d888-407b-b3df-30559d3e2b85&uid=4ca0f465dbcd41f588c0d2119c58d231

**Comment by libsgh** [comment]
阿里云文件夹下载的接口已经被关闭，下个版本会移除阿里云的文件夹下载功能
