### ISSUE TITLE
文件夹加密bug

### ISSUE THREAD

**Issue by nozomileng** [libsgh/PanIndex#211]
开启文件夹加密后，去浏览页面不输入密码直接确认，然后输入密码也不能打开文件夹就一直卡输密码那，edge，和谷歌浏览器都会触发。

**Comment by Rominwolf** [comment]
请检查一下是否开启了缓存。
如果使用了反向代理并设置了缓存，那么即使成功键入了密码也不会跳转到目录内。

**Comment by libsgh** [comment]
更新到最新版
