### ISSUE TITLE
似乎Teambition国际版无法正常登录

### ISSUE THREAD

**Issue by Cicini** [libsgh/PanIndex#216]
![20211231224416](https://user-images.githubusercontent.com/62730438/147828949-61195581-a5af-48cd-82ca-6520f50af616.png)
![20211231224450](https://user-images.githubusercontent.com/62730438/147828965-1dd577f6-af8e-4185-9527-1ab3411bfd85.png)

**Comment by libsgh** [comment]
api有修改，等下个版本修复吧

**Comment by libsgh** [comment]
v3已修复
