### ISSUE TITLE
希望能自定义网盘目录地址

### ISSUE THREAD

**Issue by Youwenqwq** [libsgh/PanIndex#219]
在panindex中设置首页账号切换为全部账号后，每个账号的地址为“d_0/”，"d_1/"等，能否提供一个选项，将这些d_0,d_1改为账号对应的名称，例如账号名为CT则显示为“localhost:33003/CT/”而不是"localhost:33003/d_0/"？
感谢

**Comment by libsgh** [comment]
下个版本已经改为网盘账号名称。可以自定义。

**Comment by libsgh** [comment]
v3版本已经实现
