### ISSUE TITLE
如何加密某个挂载的云盘

### ISSUE THREAD

**Issue by BoneAsh** [libsgh/PanIndex#222]
是否应该在加密文件夹配置中添加d_0、d_1的标识，这样可以区分开不同的云盘加密，也可以加密单独的某个云盘。现在的版本中如果路径设置为"/"，则所有盘文件夹都会加密。。

**Comment by libsgh** [comment]
下个版本，加密会用完整路径`/ali/a/b/c`，其中`ali`为网盘名称

**Comment by libsgh** [comment]
v3版本，使用`/网盘名称`作为加密路径可以对网盘进行加密
