### ISSUE TITLE
crontab 任务不执行

### ISSUE THREAD

**Issue by NoverNobida** [libsgh/PanIndex#223]
目前存在crontab任务（使用默认的参考示例）不执行的情况，见于挂载两个盘，上一个盘不执行刷新，只有下一个任务执行。
可否增加执行刷新失败消息推送特性？因为阿里云盘的token经常失效。例如通过邮箱，webhook，或者其他方式推送刷新缓存失败消息。

**Comment by libsgh** [comment]
下版会修复你提到的两个问题

**Comment by libsgh** [comment]
更新到最新版
