### ISSUE TITLE
2.0.8文件夹加密问题，不用密码也能访问

### ISSUE THREAD

**Issue by hyathlon** [libsgh/PanIndex#227]
2.0.8设置了文件夹加密，点开加密文件夹确实需要密码，但这时候在地址栏输入下级目录或文件名，是可以访问的。
还有，搜索能够搜出加密文件夹里的内容，能正常访问、下载。

**Comment by libsgh** [comment]
如果加密后还可以被搜到，可以试试重新缓存下文件。如果不知道子目录文件名，其实也能保证一定的安全性，3.x版本以文件虚拟路径替代之前的文件ID，这样就可以轻松根据路径对子目录做加密判断

**Comment by libsgh** [comment]
请使用v3版本
