### ISSUE TITLE
为什么架设后没任何反应。。

### ISSUE THREAD

**Issue by nodesire7** [libsgh/PanIndex#229]
配置都没问题 访问的时候就是访问不了。。
![QQ截图20220126153724](https://user-images.githubusercontent.com/63827263/151122154-9317b02f-d3d2-4199-98dd-3ff34f870896.png)

**Comment by libsgh** [comment]
新手建议用一键脚本部署启动

**Comment by nodesire7** [comment]
> 新手建议用一键脚本部署启动

脚本也是这样啊 只是说装好了 访问:5238端口没反应

![QQ截图20220126154238](https://user-images.githubusercontent.com/63827263/151122675-df13575c-60ed-4eed-802d-d6bfe2fe5a56.png)

**Comment by libsgh** [comment]
自己检查下 5238是否已经被占用，看下进程
```
systemctl status PanIndex
journalctl -u PanIndex.service -f
```

**Comment by nodesire7** [comment]
> 自己检查下 5238是否已经被占用，看下进程
> 
> ```
> systemctl status PanIndex
> journalctl -u PanIndex.service -f
> ```

![QQ截图20220126154848](https://user-images.githubusercontent.com/63827263/151123713-6471622e-c636-4fa6-aabf-84f97f7ec1f4.png)
![QQ截图20220126154858](https://user-images.githubusercontent.com/63827263/151123718-9dae9d33-0937-4aca-ae8a-cc7634418ece.png)
![QQ截图20220126155150](https://user-images.githubusercontent.com/63827263/151123729-1aa13dd8-9cec-4fc0-a14b-97735f989b3d.png)
一样的 我把进程结束了再重开也是不行 我的端口默认都是开的

**Comment by libsgh** [comment]
curl "http://localhost:5238/?admin"

**Comment by nodesire7** [comment]
> curl "http://localhost:5238/?admin"

会考虑支持Sharepoint吗
