### ISSUE TITLE
外链引用含有 origin 时, 产生 CORS 报错的问题.. 

### ISSUE THREAD

**Issue by zkeq** [libsgh/PanIndex#231]
之前在另一个 目录项目 上有关于这个问题的讨论 

见 https://github.com/spencerwooo/onedrive-vercel-index/discussions/313

并给出了所用技术栈的解决方法 https://github.com/spencerwooo/onedrive-vercel-index/pull/315

在本项目中的问题复现见：
https://pro.dream-plan.cn/test-2

所用的测试链接为 作者 搭建的云盘 ：
https://t1.noki.icu/d_1/%E5%9C%B0%E7%90%83Online.mp4

**Comment by libsgh** [comment]
1.  阿里云盘本身是有防盗链的
2.  加载字幕后引起的跨域你应该去问DPlayer

**Comment by zkeq** [comment]
感谢作者回复...

> Address of the track (.vtt file). Must be a valid URL. 
This attribute must be specified and its URL value must have the same origin as the document — unless the [<audio>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) or [<video>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) parent element of the track element has a [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) attribute.

因为在另一个项目中通过修复请求标头修复了这个问题....所以才跑过来提一个 issues ..

> The PR adds CORS-related headers for raw file links to make cross-origin requests redirected.
> The PR adds package cors with @types/cors which is suggested by Next offically.

对您造成的困扰表示抱歉
