### ISSUE TITLE
天翼云目前有防盗链，无法预览

### ISSUE THREAD

**Issue by chinapee** [libsgh/PanIndex#233]
因为天翼云目前有防盗链，无法预览，建议如下：
1.  使用iframe的方法
2. curl的方法
绕过防盗链设置

**Comment by libsgh** [comment]
上链接吧，我这里的Demo可以正常预览。

**Comment by chinapee** [comment]
https://pan.cfw.vip
第一个文件夹里都是mp4的教程 可以下载不能预览，第二个文件夹里的mp4格式电影 可以预览和下载

**Comment by chinapee** [comment]
好像有的有防盗链有份没有，不知道什么鬼

**Comment by chinapee** [comment]
研究了下，可能是由特征码，有些电影和视频Response应答不同，如果调用多了就会验证防盗链，189网页版不受限制，第三方会有限制。
