### ISSUE TITLE
服务器中转云盘下载

### ISSUE THREAD

**Issue by nozomileng** [libsgh/PanIndex#235]
像od盘什么的国外盘，下载是走服务器流量中转一圈而不是直接服务器获取api然后走云盘下载，并且这个为可更改项，想直连云盘下载就关闭开关，想走服务器中转流量就打开开关，这能否实现

**Comment by fabaoin** [comment]
同问，需要这个功能。一个是想隐藏云盘的实际地址，二是可以使用GOOGLE的团队盘。能否加入这个中转流量的功能？
