### ISSUE TITLE
百度统计代码不起作用

### ISSUE THREAD

**Issue by DingChang90** [libsgh/PanIndex#238]
RT，百度统计代码添加到这里后，监测提示「referrer被禁用」
放到「自定义底部信息(Footer)」和「自定义Javascript」里均不起作用。

百度搜索有答案说需要放在
<meta name="referrer" content="no-referrer" />之前

**Comment by libsgh** [comment]
为了解决阿里云盘的防盗链问题，在阿里云盘模式下页面head添加了`<meta name="referrer" content="no-referrer">`，其他网盘模式不受影响

**Comment by DingChang90** [comment]
已转用CNZZ，不受影响。
