### ISSUE TITLE
能否考虑实现前后端分离

### ISSUE THREAD

**Issue by Wittoy** [libsgh/PanIndex#24]
如  #15 所言，能否考虑前后端分离，或者前端配置文件独立化，方便自定义前端需求，而不是改代码后再进行自编译等复杂操作。

**Comment by libsgh** [comment]
PanIndex设计的初衷是部署方便，适配heroku，所以在打包的时候将html，js，css都打进到二进制文件中。如果前后端分离，即静态页面+api，页面访问时间将变长，在heroku这种网络环境不太好的部署方式中，影响比较大，由于静态页面要单独部署，也会增加一定的部署成本。如果你的需求仅仅是修改页面 比如背景，网站favicon，footer，或是css js这种操作我可以将模板页面从二进制程序中独立出来，方便修改。甚至可以自己定义喜欢的主题，但是数据渲染方式不变。

**Comment by Wittoy** [comment]
页面独立也可，这样比较方便修改。

**Comment by libsgh** [comment]
更新至v1.0.4，可以自定义页面。
