### ISSUE TITLE
Koyeb的支持

### ISSUE THREAD

**Issue by imgblz** [libsgh/PanIndex#242]
是个免费的容器
https://koyeb.com
Koyeb 预览图

在预览期间，您最多可以运行两个具有任何容器大小的服务，最大内存为 2GB。一旦我们上线，您将免费获得 5 美元/月的使用额度，相当于两个全职 Nano 实例！

**Comment by libsgh** [comment]
Koyeb我注册不上，如果支持Docker的话参考下https://github.com/libsgh/PanIndex-heroku， 简单修改就可以部署
