### ISSUE TITLE
新版本相关问题

### ISSUE THREAD

**Issue by echoiron** [libsgh/PanIndex#25]
- github无法访问导致报错
https://api.github.com/repos/libsgh/PanIndex/releases/latest
目前可通过修改服务器hosts解决此问题
140.82.114.6 api.github.com

- 初始化报错
![image](https://user-images.githubusercontent.com/52339367/108954648-1858fb00-76a8-11eb-82a6-d667e34907e2.png)

**Comment by libsgh** [comment]
有些地方github访问不好，下个版本会处理版本检测请求可能出现的异常

**Comment by echoiron** [comment]
同样的环境，换成1.0.2没有问题了
我没有安装gcc，本地暂时不能debug

**Comment by libsgh** [comment]
> 同样的环境，换成1.0.2没有问题了
> 我没有安装gcc，本地暂时不能debug

v1.0.3之前的版本问题比较多，建议直接用最新版

**Comment by echoiron** [comment]
发现一个问题，所有的189.cn被替换成pan.cn了，导致无法访问

**Comment by libsgh** [comment]
> 发现一个问题，所有的189.cn被替换成pan.cn了，导致无法访问
> 改变所在的git提交：d3a174310e2910ab0704e51de0cce6a1c0bc8f72

做多网盘支持的时候，替换掉了，后面我用了teambition盘也没测试天翼云就没发现，我重新发布下v1.0.3

**Comment by libsgh** [comment]
已重新发布v1.0.3，感谢问题反馈

**Comment by li-xunhuan** [comment]
> 已重新发布v1.0.3，感谢问题反馈

Docker镜像也更新一下吧，不然起不起来

**Comment by libsgh** [comment]
> > 已重新发布v1.0.3，感谢问题反馈
> 
> Docker镜像也更新一下吧，不然起不起来
Docker镜像已经更新，并进行了精简
![image](https://user-images.githubusercontent.com/25656088/109246465-4a3f9e00-781d-11eb-896d-dbac852419f9.png)
