### ISSUE TITLE
希望可以支持自定义视频字幕的相对路径或分离视频和字幕的目录

### ISSUE THREAD

**Issue by Rominwolf** [libsgh/PanIndex#256]
如果某个目录存在大量的视频文件，然后每个文件还对应一个字幕文件……那这个目录的文件就会显得很多，很乱，而且很不方便索引。
所以希望在未来的版本里可以实现视频文件/字幕文件的目录分离。😂

比如说目录 /videos/... 存放视频，而 /videos/subtitles/... 则负责存放字幕。

**Comment by libsgh** [comment]
路径规定死也不太好，你先通过改js简单实现，后面会做成灵活配置。

**Comment by Rominwolf** [comment]
> 路径规定死也不太好，你先通过改js简单实现，后面会做成灵活配置。

好的，那就顺便建议一下可以支持自定义更多播放器的属性了😂😂

**Comment by libsgh** [comment]
v3.0.6已更新播放设置，更多属性还是靠自己改js实现吧
