### ISSUE TITLE
[Feature] 支持将域名绑定到指定网盘功能

### ISSUE THREAD

**Issue by kasuganosoras** [libsgh/PanIndex#257]
RT，希望增加一个指定域名绑定网盘功能，当通过该域名访问时，自动展现对应网盘下的文件，同时隐藏切换到其他网盘的功能。

### 原因
天翼云盘现在不能下载超过 1GB 的文件了，所以需要使用其他网盘来储存大于 1GB 的文件，但是又不想改动原有的目录结构，因此想到可以增加这个功能来解决问题。

### 实例
比如我在阿里云盘存了有一些大于 1GB 的文件，然后在天翼云盘存了一些小于 1GB 的文件，然后我想通过 cloud-189.example.com 访问天翼云盘，cloud-ali.example.com 访问阿里云盘。

同时域名绑定是 **_可选的_**，如果不绑定域名，则正常展示默认网盘，以及显示切换到其他网盘的下拉菜单。

**Comment by libsgh** [comment]
天翼云1g文件无法下载是web端接口限制，我已经更换了接口，更新到v3.0.4
域名绑定没什么必要，现在首页可以展示所有账号，这样访问`/cloud189`就是天翼云盘，访问`/ali`就是阿里云盘，用网盘名称加以区分就行

**Comment by Cicini** [comment]
可以尝试重定向

**Comment by Cicini** [comment]
对于切换网盘的隐藏你可以考虑源码部署/自行编译，自己手动改一下前端就好

**Comment by kasuganosoras** [comment]
已经手动修改了源码实现域名绑定了，有空我整理一下代码提交 PR 吧

**Comment by libsgh** [comment]
v3.0.6已实现
