### ISSUE TITLE
账号已被限速，建议各位不要白嫖过度

### ISSUE THREAD

**Issue by kasuganosoras** [libsgh/PanIndex#26]
用来做软件分发下载，月流量预估达到 3TB 左右，现在账号已被限速到 128KB/s，无论网页还是客户端都是，建议各位不要白嫖过度。

不说了，搬数据去了（狗头

**Comment by libsgh** [comment]
会不会是月流量有什么限制，下个月速度就又好了，如果开会员不会没有什么说法就限速吧，天翼云大部分账户是15g，滥用情况还好吧，可以试试teambition，就是上传有点慢

**Comment by kasuganosoras** [comment]
我就是开了铂金会员，想着应该稳一点吧，毕竟会员介绍上写了单日不限流量的，结果还是被限速了

本来还想找客服问问的，但是想了下感觉相当于主动说明自己在白嫖（

还是算了

**Comment by renzhenqi** [comment]
> 我就是开了铂金会员，想着应该稳一点吧，毕竟会员介绍上写了单日不限流量的，结果还是被限速了
> 
> 本来还想找客服问问的，但是想了下感觉相当于主动说明自己在白嫖（
> 
> 然后又钻了下字眼，会员介绍说是单日不限上传流量，没说下载流量，如果真要扯的话应该扯不过客服，毕竟用户服务协议里面明确说了不能用第三方软件使用服务（不过不说谁知道呢（狗头
> 
> 还是算了，多一事不如少一事
> 
> PS：感觉可能可以通过开多个账号负载均衡（？）每个账号文件一样，每次下载随机从一个账号下，这样感觉应该会更稳一点
> 有空去试试
老哥  你后来怎么解决的这个问题   或者说有其他替代方案吗    天翼云直链解析这个问题

**Comment by tingyue-wu** [comment]
PanIndex搭建好后，下载是直连网盘，流量走网盘，还是流量中转搭建PanIndex的服务器的？

**Comment by libsgh** [comment]
> 下载是直连网盘，流量走网盘，还是流量中转搭建PanIndex的服

PanIndex的下载地址会通过接口的方式获取文件的直链（流量走PanIndex），最终文件下载流量还是走网盘
