### ISSUE TITLE
希望增加 Artplayer 弹幕插件支持

### ISSUE THREAD

**Issue by Reisen301** [libsgh/PanIndex#260]
Artplayer 官方插件支持加载 XML 弹幕文件，希望增加对该插件的支持，https://artplayer.org/document/en/Plugins/danmuku
另外如何在显示全部挂载账号的首页加载 README.md ？

**Comment by libsgh** [comment]
- 下版本会对视频做配置增强
- 把README.md放到第一个账号的根目录下即可显示

**Comment by libsgh** [comment]
v3.0.6已实现
