### ISSUE TITLE
每个密码都要在后台设置吗，不能直接在前端直接设置密码和改密码

### ISSUE THREAD

**Issue by vipy800** [libsgh/PanIndex#264]
每个密码都要在后台设置吗，不能直接在前端直接设置密码和改密码

**Comment by libsgh** [comment]
前端是直接对外的，直接可以修改密码会有安全问题。

**Comment by vipy800** [comment]
哦，好吧，就是感觉每次去后台很麻烦。或者可以前端管理员登陆，然后不需要密码。。这样也很好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月20日(星期天) 晚上7:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [libsgh/PanIndex] 每个密码都要在后台设置吗，不能直接在前端直接设置密码和改密码 (Issue #264)





 
前端是直接对外的，直接可以修改密码会有安全问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by libsgh** [comment]
> 哦，好吧，就是感觉每次去后台很麻烦。或者可以前端管理员登陆，然后不需要密码。。这样也很好
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月20日(星期天) 晚上7:52 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [libsgh/PanIndex] 每个密码都要在后台设置吗，不能直接在前端直接设置密码和改密码 (Issue #264) 前端是直接对外的，直接可以修改密码会有安全问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

新版本已经有这样的功能，在访问控制里设置
![image](https://user-images.githubusercontent.com/25656088/195018654-9fcd6cf5-b2e1-4b42-b944-0935e02d6076.png)
