### ISSUE TITLE
希望可以增加调用外部播放器如potplayer播放视频的功能

### ISSUE THREAD

**Issue by ssln5014** [libsgh/PanIndex#269]
### 例如[alist](https://alist.xhofe.top/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/04_%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BA%E5%AE%B6%E5%BA%AD%E7%BA%AA%E5%BF%B5%E7%9B%B8%E5%86%8C.mp4)

**Comment by libsgh** [comment]
复制链接到播放器就好了...实在不想额外加播放器按钮

**Comment by ssln5014** [comment]
> 复制链接到播放器就好了...实在不想额外加播放器按钮

好的
