### ISSUE TITLE
不止可否加入  阿里云盘  和 文件全局搜索

### ISSUE THREAD

**Issue by hais1992** [libsgh/PanIndex#27]
目前阿里云盘已经正式公测，用的人越来越多也 与 teambition盘 进行合并， API也相对简单。 可参考  https://github.com/Xhofe/alist  进行添加。

另外，每次启动的时候文件路径也已经缓存到 Sqlite数据中，是否可以根据数据库中的文件开发出文件搜索功能。

**Comment by libsgh** [comment]
- 阿里云盘一直在计划中，由于刚开始公测，它的登录依赖token，而无法通过登录实现，与PanIndex现有的配置结构不太兼容。另外群友反馈阿里云盘会ban账号。
- 下个版本会先在mdui主题支持文件夹内搜索，全局搜索看需求，也可添加。

**Comment by libsgh** [comment]
v2.0.1已加入
