### ISSUE TITLE
希望增加网盘自定义排序

### ISSUE THREAD

**Issue by longda33** [libsgh/PanIndex#273]

**Comment by nitezs** [comment]
哪个排序

**Comment by longda33** [comment]
![https://p0.meituan.net/dpgroup/25df30a00f5552aff790f48b3c035d7062560.jpg](排序)
自定义网盘位置

**Comment by libsgh** [comment]
> https://p0.meituan.net/dpgroup/25df30a00f5552aff790f48b3c035d7062560.jpg 自定义网盘位置

后台可以拖动网盘进行排序
