### ISSUE TITLE
Teambition国际版无法保存项目ID信息

### ISSUE THREAD

**Issue by Cicini** [libsgh/PanIndex#281]
每次填写了项目ID点击保存后重新点修改项目ID就空了(已弹出保存成功的信息)
目录也是无法缓存的
填写的确认是Project ID
例如`https://us.teambition.com/project/aaaaa/works/bbbbb`
项目ID填写的`aaaaa`
PanIndex版本: 3.0.6

**Comment by libsgh** [comment]
我这边测试3.0.6是没问题的。新建个新项目试试

**Comment by Cicini** [comment]
非常离谱( 还是一样的情况
还是说目录ID不能填root ？

**Comment by libsgh** [comment]
> 非常离谱( 还是一样的情况 还是说目录ID不能填root ？



> 非常离谱( 还是一样的情况 还是说目录ID不能填root ？

目录id不能root

**Comment by Cicini** [comment]
> > 非常离谱( 还是一样的情况 还是说目录ID不能填root ？
> 
> 目录id不能root

那应该填写什么呢，文档中并没有对目录ID的说明，Project ID即项目ID（目录ID填works后的内容也是相同情况）

**Comment by libsgh** [comment]
> > > 非常离谱( 还是一样的情况 还是说目录ID不能填root ？
> > 
> > 
> > 目录id不能root
> 
> 那应该填写什么呢，文档中并没有对目录ID的说明，Project ID即项目ID（目录ID填works后的内容也是相同情况）

works前面的是项目ID，后面的是目录ID，设置的没错的话是可以的。
Project ID没有回显，但是数据库里面的数据是存在的，这个显示错误会在下版本修复。虽然没有显示项目ID，但是不影响使用。

**Comment by Cicini** [comment]
> > > > 非常离谱( 还是一样的情况 还是说目录ID不能填root ？
> > > 
> > > 
> > > 目录id不能root
> > 
> > 
> > 那应该填写什么呢，文档中并没有对目录ID的说明，Project ID即项目ID（目录ID填works后的内容也是相同情况）
> 
> works前面的是项目ID，后面的是目录ID，设置的没错的话是可以的。 Project ID没有回显，但是数据库里面的数据是存在的，这个显示错误会在下版本修复。虽然没有显示项目ID，但是不影响使用。

测试之后确实可以正常进行缓存，建议在文档中增加Teambition 项目的文件目录填写说明，此外还有一个BUG，当触发无回显后修改Project ID数据库(siteid)中并不会变更
