### ISSUE TITLE
heroku部署失败

### ISSUE THREAD

**Issue by wwalt1a** [libsgh/PanIndex#283]
提示We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy. 
看了下前面的https://github.com/libsgh/PanIndex/issues/230#issuecomment-1085728302 并没找到怎么解决

**Comment by libsgh** [comment]
heroku已经独立到下面的仓库了，不需要Fork项目直接点击Button就可以部署
https://github.com/libsgh/PanIndex-heroku

**Comment by libsgh** [comment]
我改了一下仓库的名字，现在可以了，你再试试。

**Comment by libsgh** [comment]
> https://heroku.com/deploy?template=https://github.com/libsgh/PanIndex-heroku.git

https://heroku.com/deploy?template=https://github.com/libsgh/PanIndex-h.git
