### ISSUE TITLE
反代出现挂载不能播放视频和音频问题

### ISSUE THREAD

**Issue by nozomileng** [libsgh/PanIndex#286]
版本3.0.6
挂载od、中转浏览、api直连缓存。 直接ip访问能播放视频、音频，直接使用域名反代会出现无法加载视频，音频。cf cdn、ip转发也一样无法访问，但是图片可以加载

**Comment by libsgh** [comment]
‘直接使用域名反代’，不清楚你是如果和配置的，配置的加速域名是否生效
