### ISSUE TITLE
请问这个可以部署到腾讯云云函数吗？

### ISSUE THREAD

**Issue by Youngolo** [libsgh/PanIndex#287]
[腾讯云，云函数](https://console.cloud.tencent.com/scf/list)
如果可以的话，能否出个教程啊

**Comment by libsgh** [comment]
不可以，因为配置是存储在数据库中。

**Comment by xtyzhen** [comment]
可以使用阿里云云函数服务，Go自定义执行，使用参数传递，连接外部数据库部署。腾讯云未测试，但基本同理。
连接统一数据库时也可实现单数据可下的多服务器负载均衡。

**Comment by ghostWindows-files** [comment]
> 可以使用阿里云云函数服务，Go自定义执行，使用参数传递，连接外部数据库部署。腾讯云未测试，但基本同理。 连接统一数据库时也可实现单数据库下的多服务器负载均衡。

请教，如何连接外部数据库
