### ISSUE TITLE
求助安装方法

### ISSUE THREAD

**Issue by beizi1754** [libsgh/PanIndex#29]
能否给个说明。告知下安装方法。研究半天没搞定。。。
愿意红包酬谢。

**Comment by libsgh** [comment]
在线文档
https://libsgh.github.io/PanIndex/

**Comment by beizi1754** [comment]
收到。我去折腾去。那啥。能够给个二维码。表示下感谢！

**Comment by beizi1754** [comment]
小白一个。是在不会安装了。。。

**Comment by libsgh** [comment]
> 小白一个。是在不会安装了。。。

https://libsgh.github.io/PanIndex/#/?id=%E6%8D%90%E5%8A%A9，你加下电报群或是我的qq，在文档底部有联系方式

**Comment by beizi1754** [comment]
好的

**Comment by beizi1754** [comment]
已捐助。已加Q
