### ISSUE TITLE
搜索输入框的文本输入字母长度限制

### ISSUE THREAD

**Issue by nameyou486** [libsgh/PanIndex#291]
可能被利用搜索文本框没有限制的这一点来进行一个服务器的攻击，
- 建议给文本框的标签`input`添加一个属性`maxlength="30"`来进行一个文本输入的限制
相关code如下
```
<input type="text" placeholder="搜索文件（夹）" class="search 	mdui-textfield-input search-input" value="" maxlength="10">
```

**Comment by libsgh** [comment]
`maxlength="30"`会影响搜索框显示，会直接限制了搜索文字的长度。

**Comment by nameyou486** [comment]
懂了，直接限制了搜索文字的长度对于其他用途不是很好
