### ISSUE TITLE
heroku数据库1万行的限制有办法绕过吗?

### ISSUE THREAD

**Issue by foxdodo** [libsgh/PanIndex#293]
这是否跟我设置了`完全缓存`有关? 才挂了一个OD就8k行了. 大佬有办法绕过数据库限制吗? 或者如何设置能减小数据库

![pi](https://user-images.githubusercontent.com/3275698/162773102-45f3a349-6f70-479c-800d-844ef8440ea4.PNG)

**Comment by yearnzest** [comment]
可否考虑添加其他数据库支持（pgsql,mysql），因为在railway上部署是可以添加pgsql的（不限数据行数），我测试过，目前panindex在railway上部署如果用默认的sqlite，数据会丢失，就跟残废了一样。

**Comment by libsgh** [comment]
> 可否考虑添加其他数据库支持（pgsql,mysql），因为在railway上部署是可以添加pgsql的（不限数据行数），我测试过，目前panindex在railway上部署如果用默认的sqlite，数据会丢失，就跟残废了一样。

支持postgres的，使用模板（Button）创建的app，已经设置好了

**Comment by yearnzest** [comment]
> > 可否考虑添加其他数据库支持（pgsql,mysql），因为在railway上部署是可以添加pgsql的（不限数据行数），我测试过，目前panindex在railway上部署如果用默认的sqlite，数据会丢失，就跟残废了一样。
> 
> 支持postgres的，使用模板（Button）创建的app，已经设置好了

那如果用render部署呢，需要手动添加环境变量吗？

**Comment by libsgh** [comment]
> > > 可否考虑添加其他数据库支持（pgsql,mysql），因为在railway上部署是可以添加pgsql的（不限数据行数），我测试过，目前panindex在railway上部署如果用默认的sqlite，数据会丢失，就跟残废了一样。
> > 
> > 
> > 支持postgres的，使用模板（Button）创建的app，已经设置好了
> 
> 那如果用render部署呢，需要手动添加环境变量吗？

需要，不过不建议用render，因为配置会重置
