### ISSUE TITLE
天翼云刷新不出来文件问题

### ISSUE THREAD

**Issue by xuebiya** [libsgh/PanIndex#295]
天翼云有几个exe一直都刷不出来，2.0.9却可以，已经尝试了重新安装都不行

**Comment by xuebiya** [comment]
是的，其他文件都正常，就是那几个文件不行

**Comment by libsgh** [comment]
可以把天翼云文件分享给我测试一下

**Comment by xuebiya** [comment]
https://gz2.xuebiw.cn/%E6%97%85%E4%B8%9A/MicrosoftOffice2003v7.exe

**Comment by libsgh** [comment]
> https://gz2.xuebiw.cn/%E6%97%85%E4%B8%9A/MicrosoftOffice2003v7.exe

我这里测试时正常得306

**Comment by xuebiya** [comment]
我再试试

**Comment by xuebiya** [comment]
新版的还是不行 2.0.9的可以

**Comment by libsgh** [comment]
> 新版的还是不行 2.0.9的可以

确定没有隐藏什么的吧，你可以尝试把原来的文件 重命名、重新上传试试

**Comment by xuebiya** [comment]
也不行。包含的文件夹也是刷新不出来

**Comment by xuebiya** [comment]
https://gz2.xuebiw.cn/ 2.0.9
http://cdn.xuebiw.cn:5238 3.0.6
两者配置一样
3.0.6刷不出来

**Comment by libsgh** [comment]
> https://gz2.xuebiw.cn/ 2.0.9 http://cdn.xuebiw.cn:5238 3.0.6 两者配置一样 3.0.6刷不出来

你这里一个文件都没有，一开始你描述的是部分文件不展示，2.x，3.x配置不通用，不能用一套，最好用一套新的配置

**Comment by xuebiya** [comment]
我已经在天翼云上新创建了一个新的文件夹，目录id也是重新填写了，文件还是那些，也是加载不出来

**Comment by libsgh** [comment]
2.x，3.x不要用一套配置数据，如果还有问题再打开此issue
