### ISSUE TITLE
求教用Cloudflare反代下载地址该如何设置?

### ISSUE THREAD

**Issue by foxdodo** [libsgh/PanIndex#296]
在onedrive的`中转地址`中填写CF worker似乎不会生效.
尝试写`xxx-my.sharepoint.com,xxx.fapcraft.workers.dev,`或者`xxx-my.sharepoint.com|xxx.fapcraft.workers.dev,`都无法生效, 中转还是走的本机流量. 请问是格式不对吗?

**Comment by libsgh** [comment]
xxx-my.sharepoint.com|xxx.fapcraft.workers.dev

**Comment by foxdodo** [comment]
> `xxx-my.sharepoint.com|xxx.fapcraft.workers.dev` 由于现在修改有BUG，需要在添加网盘的时候指定（修改无效）

这个格式是对的? 不用加协议头吧?

**Comment by libsgh** [comment]
> > `xxx-my.sharepoint.com|xxx.fapcraft.workers.dev` 由于现在修改有BUG，需要在添加网盘的时候指定（修改无效）
> 
> 这个格式是对的? 不用加协议头吧?

对的，不需要加请求头

**Comment by foxdodo** [comment]
成了, 感谢大佬
