### ISSUE TITLE
希望作者能发布一下arm版

### ISSUE THREAD

**Issue by KyAaron** [libsgh/PanIndex#3]
作者，能不能发布一下arm版的程序，我想在arm设备上运行!
armv7(32位)以及arm64位!

**Comment by libsgh** [comment]
添加了arm32和64版本，arm默认是6，看看是否满足你的需要。

**Comment by KyAaron** [comment]
> 添加了arm32和64版本，arm默认是6，看看是否满足你的需要。

大佬，arm的两个版本似乎都不行
![IMG_20201023_160659](https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201023_160659.jpg)
![IMG_20201023_161713](https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201023_161713.jpg)

**Comment by libsgh** [comment]
[PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5443854/PanIndex-v1.0.0-linux-arm64.tar.gz)
[PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5443855/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)

因为用到了mattn/go-sqlite3，cgo的交叉编译有点蛋疼，我现在用的gh action发布的arm版本有问题，所以我本地打了两个包，你测试一下，看能否运行。

**Comment by KyAaron** [comment]
> [PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5443854/PanIndex-v1.0.0-linux-arm64.tar.gz)
> [PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5443855/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
> 
> 因为用到了mattn/go-sqlite3，cgo的交叉编译有点蛋疼，我现在用的gh action发布的arm版本有问题，所以我本地打了两个包，你测试一下，看能否运行。

大佬貌似还是不行呀
https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201030_202538.jpg

**Comment by libsgh** [comment]
> > [PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5443854/PanIndex-v1.0.0-linux-arm64.tar.gz)
> > [PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5443855/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
> > 因为用到了mattn/go-sqlite3，cgo的交叉编译有点蛋疼，我现在用的gh action发布的arm版本有问题，所以我本地打了两个包，你测试一下，看能否运行。
> 
> 大佬貌似还是不行呀
> https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201030_202538.jpg

你加我qq：359916450，两个版本都不行么

**Comment by libsgh** [comment]
网上查了查，可能是你的GLBC版本较低导致的。使用xgo的`arm-linux-gnueabi-gcc-5`重新构建了两个包，我在arm64v8/ubuntu,和arm32v7/ubuntu中测试通过，你再测试一下吧。
[PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5487337/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
[PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5487344/PanIndex-v1.0.0-linux-arm64.tar.gz)

**Comment by KyAaron** [comment]
> 网上查了查，可能是你的GLBC版本较低导致的。使用xgo的`arm-linux-gnueabi-gcc-5`重新构建了两个包，我在arm64v8/ubuntu,和arm32v7/ubuntu中测试通过，你再测试一下吧。
> [PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5487337/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
> [PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5487344/PanIndex-v1.0.0-linux-arm64.tar.gz)

大佬，这次能运行了，但是打不开网址及对应端口的访问界面
https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201030_202538.jpg

**Comment by libsgh** [comment]
> > 网上查了查，可能是你的GLBC版本较低导致的。使用xgo的`arm-linux-gnueabi-gcc-5`重新构建了两个包，我在arm64v8/ubuntu,和arm32v7/ubuntu中测试通过，你再测试一下吧。
> > [PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5487337/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
> > [PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5487344/PanIndex-v1.0.0-linux-arm64.tar.gz)
> 
> 大佬，这次能运行了，但是打不开网址及对应端口的访问界面
> https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201104_230315.jpg

刚试了下 可以访问，你打不开链接浏览器有什么提示吗？能否截个图？另外防火墙之类的开没开端口？可以在服务器上用下面命令做下测试。
```bash
$ curl -I http://localhost:8080
```

**Comment by KyAaron** [comment]
> > > 网上查了查，可能是你的GLBC版本较低导致的。使用xgo的`arm-linux-gnueabi-gcc-5`重新构建了两个包，我在arm64v8/ubuntu,和arm32v7/ubuntu中测试通过，你再测试一下吧。
> > > [PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5487337/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
> > > [PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5487344/PanIndex-v1.0.0-linux-arm64.tar.gz)
> > 
> > 
> > 大佬，这次能运行了，但是打不开网址及对应端口的访问界面
> > https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201104_230315.jpg
> 
> 刚试了下 可以访问，你打不开链接浏览器有什么提示吗？能否截个图？另外防火墙之类的开没开端口？可以在服务器上用下面命令做下测试。
> 
> ```shell
> $ curl -I http://localhost:8080
> ```
> 
> 下面是正常的日志，我看你的截图里面，目录缓存还没有刷新就停止了，网盘如果文件较多，多等一会儿
> ![image](https://user-images.githubusercontent.com/25656088/98195437-b8a1dd00-1f5c-11eb-8914-66ac9e3d0edc.png)

大佬，是真的没反应，我用的小号，里面仅存了一点点视频文件
https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201105_143140.jpg
https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201105_143324.jpg

**Comment by libsgh** [comment]
> > > > 网上查了查，可能是你的GLBC版本较低导致的。使用xgo的`arm-linux-gnueabi-gcc-5`重新构建了两个包，我在arm64v8/ubuntu,和arm32v7/ubuntu中测试通过，你再测试一下吧。
> > > > [PanIndex-v1.0.0-linux-arm32-v7.tar.gz](https://github.com/libsgh/PanIndex/files/5487337/PanIndex-v1.0.0-linux-arm32-v7.tar.gz)
> > > > [PanIndex-v1.0.0-linux-arm64.tar.gz](https://github.com/libsgh/PanIndex/files/5487344/PanIndex-v1.0.0-linux-arm64.tar.gz)
> > > 
> > > 
> > > 大佬，这次能运行了，但是打不开网址及对应端口的访问界面
> > > https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201104_230315.jpg
> > 
> > 
> > 刚试了下 可以访问，你打不开链接浏览器有什么提示吗？能否截个图？另外防火墙之类的开没开端口？可以在服务器上用下面命令做下测试。
> > ```shell
> > $ curl -I http://localhost:8080
> > ```
> > 
> > 
> > 下面是正常的日志，我看你的截图里面，目录缓存还没有刷新就停止了，网盘如果文件较多，多等一会儿
> > ![image](https://user-images.githubusercontent.com/25656088/98195437-b8a1dd00-1f5c-11eb-8914-66ac9e3d0edc.png)
> 
> 大佬，是真的没反应，我用的小号，里面仅存了一点点视频文件
> https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201105_143140.jpg
> https://kyaarin.coding.net/p/xbtc/d/xbtc/git/raw/master/images/IMG_20201105_143324.jpg

看你的日志没有出现目录缓存刷新的信息，所以程序还没有启动完成，因此你肯定是访问不了服务的，你最好提供下你的账号和root_id否则我很难定位你的问题。
