### ISSUE TITLE
天翼云排序问题

### ISSUE THREAD

**Issue by fantastlcok** [libsgh/PanIndex#30]
看了 #17 ，我测试还是有问题。
遇到的问题：
PanIndex文件排序规则为修改时间排序，天翼云盘设置排序为根据文件名排序。
PanIndex无法同步天翼云盘文件排序设置。

**Comment by libsgh** [comment]
刚看了一下，貌似是接口默认排序有变化，以前是`orderBy=3&order=DESC`现在是`orderBy=1&order=ASC`
1,2,3分别对应文件名，大小和修改时间
下个版本我会同步修改，感谢反馈

**Comment by libsgh** [comment]
已在2.0.0修改默认排序
