### ISSUE TITLE
在设置了OneDrive的分流的时候发现无法使用程序的文件夹加密的功能，是什么原因？

### ISSUE THREAD

**Issue by nameyou486** [libsgh/PanIndex#302]
## 在设置了OneDrive的分流的时候发现无法使用程序的文件夹加密的功能
之前只有一个网盘是正常的，之后我设置了一个网盘作为分流就发现网站文件夹不用密码就可以进入，我也尝试直接更改密码，但是也是无法解决这个问题。是什么原因呀？求解

**Comment by libsgh** [comment]
用分流的路径前缀重新设置下密码

**Comment by nameyou486** [comment]
![image](https://user-images.githubusercontent.com/60727068/164233968-5d4b0bd4-d8b7-465a-839b-9e77c6c37e6d.png)
我觉得可能是我这边操作的一个问题，我需要给ONS一个密码，我是直接复制的上方图片中我选择的一段设置的密码
不知道我这样的操作是否出错
- 网盘两方的文件都是一样的

**Comment by libsgh** [comment]
比如你有两个网盘`A`,`B`,创建分流`C`，那么加密就是`/C/xxx`，这里的是文件ID，3.x是用虚拟路径进行加密的
比如你的访问地址是http://localhost/C/xxx，加密xxx文件夹，就是/C/xxx
