### ISSUE TITLE
这情况是不是只能删数据库了?

### ISSUE THREAD

**Issue by foxdodo** [libsgh/PanIndex#306]
设的定时刷新完全缓存, 然后过了一晚变成了这样, OD所有文件都变成4个同名文件, 文件数量和数据库容量翻了4倍
![image](https://user-images.githubusercontent.com/3275698/165017546-13835ff2-f694-42fe-a7ea-7272f15e0585.png)
![image](https://user-images.githubusercontent.com/3275698/165017959-28b07a43-c392-4533-9aa4-2398c7222e29.png)

heroku搭建, 用的其他网站的postgres数据库, 同一环境及设置下阿里云盘则正常

**Comment by libsgh** [comment]
文件重复的原因是你的cron配置有问题，在连续2分钟内同一账号执行了缓存刷新

可以把缓存策略那里更改成其他的 再改回来，会重新再缓存
