### ISSUE TITLE
有无计划出个api呀，想用阿里云盘直链搭建图床

### ISSUE THREAD

**Issue by xiaolan1314** [libsgh/PanIndex#307]
想用阿里云盘直链搭建图床，但是阿里云盘直链是个下载链接，放到网站上根本加载不了。。。。。如果能出api返回图片的预览地址（原图）就好了！

**Comment by libsgh** [comment]
1. 阿里云盘的下载直链有防盗链
2. api预览只能中转，服务器流量、速度都是个考验

基于上面两点，不适合做图床
