### ISSUE TITLE
Pdf.js CDN问题

### ISSUE THREAD

**Issue by YingmoY** [libsgh/PanIndex#309]
请问我选择了国内CDN后浏览器清除缓存后检查时Pdf.js仍显示jsdelivr，已经重装了最新版本，请问这个应该怎么解决，谢谢！
![image](https://user-images.githubusercontent.com/94264391/166095838-25bc5d38-54e1-47c3-a26a-b6caa1837196.png)

**Comment by libsgh** [comment]
因为pdf.js我没有找到国内cdn，就还是用了jsdelivr，jsdelivr国内访问不太好，我下版本会替换成unpkg

**Comment by YingmoY** [comment]
> 因为pdf.js我没有找到国内cdn，就还是用了jsdelivr，jsdelivr国内访问不太好，我下版本会替换成unpkg

或许可以考虑一下饿了么cdn🤔
https://npm.elemecdn.com/pdfh5@1.4.2/js/pdf.js

**Comment by libsgh** [comment]
> > 因为pdf.js我没有找到国内cdn，就还是用了jsdelivr，jsdelivr国内访问不太好，我下版本会替换成unpkg
> 
> 或许可以考虑一下饿了么cdn🤔 https://npm.elemecdn.com/pdfh5@1.4.2/js/pdf.js

Good idea.

**Comment by YingmoY** [comment]
> 因为pdf.js我没有找到国内cdn，就还是用了jsdelivr，jsdelivr国内访问不太好，我下版本会替换成unpkg

饿了么的npm非常的全，基本上是完整镜像

**Comment by libsgh** [comment]
> > 因为pdf.js我没有找到国内cdn，就还是用了jsdelivr，jsdelivr国内访问不太好，我下版本会替换成unpkg
> 
> 饿了么的npm非常的全，基本上是完整镜像

已替换，感谢！
