### ISSUE TITLE
请问armv7是用什么工具编译出来的呢

### ISSUE THREAD

**Issue by guaosi** [libsgh/PanIndex#31]
我想自己编译armv7，下了xgo，用 CC=arm-linux-gnueabihf-gcc-5
可以运行，但是打开界面时空白，不知道您是用什么工具编译全平台的呢？

**Comment by libsgh** [comment]
armv7我有编译啊，可以参考这两个xgo项目
https://github.com/crazy-max/xgo
https://github.com/techknowlogick/xgo

**Comment by guaosi** [comment]
使用techknowlogick/xgo与packr2已解决
