### ISSUE TITLE
可以添加一个指定范围搜索吗,在一个盘中搜索

### ISSUE THREAD

**Issue by JerryYang-git** [libsgh/PanIndex#312]
# 原因
我挂载了多个网盘，可以通过左上角的切换器进行一个切换，分别是影视和小说的盘，但是在进行一个搜索作品名字的时候，还是会把所有包含关键字的文件搜索出来，出来的文件列表很多

- 所以就想需要一个范围性搜索的一个搜索，如搜索全部或搜索当前目录下或者当前网盘下文件的这样的切换按钮开关，来进行一个更好的搜索

**Comment by libsgh** [comment]
目前的前端搜索框不太好加按钮开关，如果是这样的话可能要加个弹出层，设置高级搜索

**Comment by JerryYang-git** [comment]
![搜索演示1 00_00_00-00_00_30](https://user-images.githubusercontent.com/60727068/171989523-17e8b71a-ee6c-4618-9205-a9d3f16d4faf.gif)
上面的站点设置了搜索框的宽度，让其在不点击搜索的时候可以显示输入回车搜索，在点击搜索的时候会完全展开搜索
所以，是不是可以在点击搜索展开的地方下面添加有关”高级搜索“的按钮啥的，通过点击🔍按钮的时候展开高级搜索
