### ISSUE TITLE
苹果IOS设备无法在线播放视频

### ISSUE THREAD

**Issue by DingChang90** [libsgh/PanIndex#313]
安卓手机没有问题，所有苹果IOS设备都没有办法播放在线视频，这是因为啥呀？

**Comment by DingChang90** [comment]
播放器使用的「ArtPlayer 4.3.4」， 能否增加兼容IOS设备的播放器呢

**Comment by libsgh** [comment]
播放的hls(m3u8)吗？

**Comment by DingChang90** [comment]
> 

播放的是mp4、rmvb、MKV、TS这种格式的影片。

**Comment by libsgh** [comment]
> > 
> 
> 播放的是mp4、rmvb、MKV、TS这种格式的影片。

web播放支持的视频音频格式有限，请把视频转换成h264 + aac的格式，确保可以正常播放。
