### ISSUE TITLE
WebDAV不可用

### ISSUE THREAD

**Issue by zpljd258** [libsgh/PanIndex#315]
Hi There，

我尝试通过docker部署了panindex，并且在admin页面打开了webdav。

透过http://mydomain.com:5238连接，并且尝试了自带的webdav/1234的账号密码或者自定义账号密码均未能连接。

我在panindex上绑定了我的阿里云盘。

客户端使用了macOS的访达/infuse的webdav连接。

其中macOS的访达近能出现账号密码验证页面后直接报错。infuse可以看到我的阿里云盘/root目录下的文件夹，但是点击文件夹后无法访问内容。

**Comment by libsgh** [comment]
网盘的根目录是否是root？缓存模式是怎样的？用raidrive是否可以挂载？

**Comment by JackySmith** [comment]
在苹果系统下，访达 连接服务器：使用 http://域名:5238   ,填 webdav 密码1234， 确实 登陆不了。 5238端口已开。raidrive没有找到苹果版

**Comment by zpljd258** [comment]
> 网盘的根目录是否是root？缓存模式是怎样的？用raidrive是否可以挂载？

网盘的根目录是否是root？
是root

缓存模式是怎样的？
见图。

用raidrive是否可以挂载？
很抱歉，我没有尝试过这个，并没有这个工具。

辛苦您查看了
<img width="873" alt="image" src="https://user-images.githubusercontent.com/11162658/167612198-07aeadf2-b193-43ae-beca-5035d0721446.png">
<img width="939" alt="image" src="https://user-images.githubusercontent.com/11162658/167612274-aa7965d6-83d6-459d-95a4-ec579addc249.png">

**Comment by zhanbao2000** [comment]
同样的问题

启用webdav功能之后，使用raidrive、windows网络位置、es文件浏览器均可以正常看到webdav路径下的文件和文件夹，但其中所有的文件均无法访问，所有的目录打开均为空（实际并非空目录）

版本：3.0.8
挂载方式：
![图片](https://user-images.githubusercontent.com/29254102/170832927-c90e2b24-c211-4bbc-9f7a-006f41dd586d.png)
webdav设置：
![图片](https://user-images.githubusercontent.com/29254102/170832918-e2193da9-1ef3-4d91-a433-f7e8784ddb80.png)

附加：
网盘的根目录是否是root
不是，并且我试过将网盘的根目录换成root，bug依旧

**Comment by ma0shu** [comment]
同样问题：
1、Linux在终端使用 mount -t davfs 后挂载的目录为空，同上
2、在Gnome 文件管理中挂载失败，提示“无法访问位置：消息已经在会话队列中”
3、使用python包webdav4可以上传文件，但是会丢失文件名（天翼网盘变为时间戳，本地文件变为用户名），内容正常

**Comment by kanadeblisst** [comment]
用RaiDrive也是只能看到文件夹，无法看到文件夹下的文件

**Comment by libsgh** [comment]
最新版优化了webdav的兼容性，可以试试开发版
