### ISSUE TITLE
大佬可以添加远程数据库支持么

### ISSUE THREAD

**Issue by decadeicey** [libsgh/PanIndex#318]
比如通过环境变量设置 数据库的账号密码端口主机啥的 就可以在那些重启实例后删数据的平台部署了 比如render koyeb之类的

**Comment by libsgh** [comment]
可以的，config.json里面的配置都有对应的环境变量

**Comment by decadeicey** [comment]
大佬 变量 没有db_host db_port db_user db_name之类的吗
比如我注册了一个remotemysql
怎么跟config.json里的变量对应呢

用户名：db user

数据库名称： dbname

密码：db password

服务器：remotemysql.com

端口：3306
