### ISSUE TITLE
视频能否引用到个人网站使用

### ISSUE THREAD

**Issue by sw586** [libsgh/PanIndex#327]
![image](https://user-images.githubusercontent.com/24788222/173191014-56fef5c5-faa2-471f-a681-52b8da4a36bc.png)

测试了下，貌似无法播放

**Comment by libsgh** [comment]
阿里云盘的下载地址有防盗链策略，无法外链引用，除非像PanIndex一样设置
`<meta name="referrer" content="no-referrer">`
