### ISSUE TITLE
页面请求 gstatic 缓慢

### ISSUE THREAD

**Issue by wshon** [libsgh/PanIndex#329]
你好，我在系统配置中将 静态资源cdn 配置项改为 本机 后，发现加载页面会出现卡顿。查看网络请求后发现有两个 gstatic 的字体请求加载缓慢，后发现是在如下代码中定义

https://github.com/libsgh/PanIndex/blob/20b0a1122ccffa22ec971499379ae1f4af51aa1d/static/css/index.css#L80

请问是否可以将其移除，或修改为其他方式。

**Comment by libsgh** [comment]
下版本改成本地的字体

**Comment by libsgh** [comment]
新版已改用cdn
