### ISSUE TITLE
更换部分网盘挂在方式

### ISSUE THREAD

**Issue by wotime** [libsgh/PanIndex#333]
其实个人也用Panindex用了很久了，个人感觉在整个页面舒适度中Panindex看起来最舒心，用过多款不同软件，且panindex挂载支持网盘也多……
有些许小建议，不知能不能实现:
1.onedrive登陆提供多种选项，默认使用程序自带的应用注册，无需自己去“应用注册”，毕竟账号多的时候挺繁琐的……
2.同时保留onedrive用自己应用注册的方式进行挂载；商业版onedrive可考虑开房webdev去挂载……
3.Teambition挂在方式要求输入账号密码改为输入cookies以及project等必要信息，境外服务器环境中出现teambition自动登陆失败的情况，友商软件cookies就不会如此。
4.加密文件夹可以考虑检查文件夹内是否含有“Password.txt”文件进行加密

**Comment by libsgh** [comment]
1. onedrive国际版api是不通用的吧，世纪互联好像是可以用一个，这方面我不太了解，应用注册一次就好了
2. 至于商业版onedrive，如果可以支持webdav的话，PanIndex本身是支持webdav协议的可以直接选择该协议挂载
3. Teambition我在外服中是可以稳定密码登录的，如果改为cookie，因为有有效期，如果失效的话，更新是很麻烦的
4. 加密文件夹已可以通过后台随意进行配置，如果使用密码文件 那会降低目录访问的效率，去检索密码文件会耗费比较多的时间，不会采用这种方式
