### ISSUE TITLE
文件设置隐藏之后还是能被搜索

### ISSUE THREAD

**Issue by JerryYang-git** [libsgh/PanIndex#340]
Onedrive盘，DB缓存模式，设置`/动漫`文件夹隐藏  
在搜索时，这个以动漫命名的文件夹无法被搜索到  
但是文件下的子文件/夹，比如`游戏人生`或`MKV`这样的文件/夹还是会被搜索到

**Comment by libsgh** [comment]
这个是bug,可以先用下dev版本，修复了

**Comment by libsgh** [comment]
v3.0.9已修复
