### ISSUE TITLE
分享出去的链接默认是管理员登录状态，会看得到全部文件

### ISSUE THREAD

**Issue by starlight02** [libsgh/PanIndex#341]
我想让从分享链接进去的只能看见被分享的目录或文件，而不是整个存储😰
需要做什么配置吗？还是说无法修改...

**Comment by libsgh** [comment]
新版增加了访问控制，你可以体验一下dev版本

**Comment by starlight02** [comment]
> 新版增加了访问控制，你可以体验一下dev版本

请问该如何使用 Dev 版本？我使用了 docker 部署

**Comment by libsgh** [comment]
> > 新版增加了访问控制，你可以体验一下dev版本
> 
> 请问该如何使用 Dev 版本？我使用了 docker 部署

程序在/app下面，可以替换可执行程序重启就行

**Comment by starlight02** [comment]
> > > 新版增加了访问控制，你可以体验一下dev版本
> > 
> > 
> > 请问该如何使用 Dev 版本？我使用了 docker 部署
> 
> 程序在/app下面，可以替换可执行程序重启就行

我的宿主机为 Linux x86_64，在 [nightly.link](https://nightly.link/libsgh/PanIndex/workflows/nightly-build/dev) 下载 [PanIndex-linux-amd64](https://nightly.link/libsgh/PanIndex/workflows/nightly-build/dev/PanIndex-linux-amd64) 这个版本，使用 `docker ps` 命令替换 `PanIndex` 程序后，容器一直在重启中，状态为 `Restarting (127) Less than a second ago`，无法正常运行，使用 `docker logs 容器id` 无法也没有看见任何错误信息。

请求帮助，接下改怎么办？

**Comment by libsgh** [comment]
> > > > 新版增加了访问控制，你可以体验一下dev版本
> > > 
> > > 
> > > 请问该如何使用 Dev 版本？我使用了 docker 部署
> > 
> > 
> > 程序在/app下面，可以替换可执行程序重启就行
> 
> 我的宿主机为 Linux x86_64，在 [nightly.link](https://nightly.link/libsgh/PanIndex/workflows/nightly-build/dev) 下载 [PanIndex-linux-amd64](https://nightly.link/libsgh/PanIndex/workflows/nightly-build/dev/PanIndex-linux-amd64) 这个版本，使用 `docker ps` 命令替换 `PanIndex` 程序后，容器一直在重启中，状态为 `Restarting (127) Less than a second ago`，无法正常运行，使用 `docker logs 容器id` 无法也没有看见任何错误信息。
> 
> 请求帮助，接下改怎么办？

我构建了dev分支的docker镜像，拉这个tag吧iicm/pan-index:dev

**Comment by starlight02** [comment]
访问控制中只有`登录`和`公开`两个模式可用，其他模式选择后主页会显示 `404`，是还在开发中吗？

**Comment by libsgh** [comment]
访问控制四种模式：
1. 公开：自由访问任何未加密、未隐藏的目录、文件
2. 仅直链：仅可访问文件下载直链，访问目录会返回404，文件的链接需要自己根据路径手动拼接
3. 直链+预览：可访问文件下载直链、及文件预览页面，访问目录也会返回404
4. 登录：访问任意文件、目录均需要登录，登录后可以正常访问目录、文件

你可以按照你的需求配合文件加密 组合使用

**Comment by starlight02** [comment]
好的，感谢作者
