### ISSUE TITLE
希望支持小龙云盘

### ISSUE THREAD

**Issue by whws** [libsgh/PanIndex#347]
小龙云盘是四川星河飞天科技有限公司打造的一款安全可靠的存储工具，它是一个基于区块链理念、依托IPFS（InterPlanetary File System）的去中心化分布式存储应用；提供无限存储空间、海量资源共享、跨界极速传输等功能，实现自由分享的同时充分保护用户的隐私
https://www.stariverpan.com/download.html

**Comment by libsgh** [comment]
不会去支持一些小众云盘
