### ISSUE TITLE
希望支持腾讯微云

### ISSUE THREAD

**Issue by whws** [libsgh/PanIndex#349]
这个是腾讯旗下的网盘，会员便宜，也大众，希望你能支持挂载。
网盘链接:https://www.weiyun.com/

**Comment by whws** [comment]
希望不要再取消我的建议了，那个小龙云盘不久就会大众化的，还是希望能够支持。

**Comment by libsgh** [comment]
你要知道不是所有的网盘都能随便添加的，如果你有能力可以pr，另外你说的小龙云盘，我都没听过，不过欢迎pr
