### ISSUE TITLE
Heroku deloy

### ISSUE THREAD

**Issue by yesyeahvh123** [libsgh/PanIndex#354]
Hello sir, heroku is no longer free, can you add other deployment options?
I recommend alternative platforms like Vercel, Glitch

**Comment by libsgh** [comment]
Any pass platform that supports docker or golang can be deployed if it supports one of the databases SQLite, MySQL and Postgres. Vercel, glitch seems unable to deploy panindex. You can take a look at the links below, which may be helpful to you.

https://libsgh.github.io/PanIndex/#/quickstart?id=%e5%85%b6%e4%bb%96%e5%b9%b3%e5%8f%b0%e9%83%a8%e7%bd%b2

**Comment by yesyeahvh123** [comment]
Can you add Vercel? It have Upstash database

**Comment by libsgh** [comment]
There is no deployment support for vercel, vercel is only suitable for deploying static sites.
