### ISSUE TITLE
阿里云盘下载报错

### ISSUE THREAD

**Issue by wqcblog** [libsgh/PanIndex#356]
对于大文件下载，偶发性出现这种问题，请问是什么原因造成的呢，谢谢
![图片](https://user-images.githubusercontent.com/82157125/189059058-37cf4c00-e396-409a-b624-adc637e54568.png)

**Comment by hhun** [comment]
我下载大文件提示 `403 Hotlink Forbidden`

**Comment by hhun** [comment]
> 我下载文件提示 `403 Hotlink Forbidden` 是部署在 `Railway` 里面，这是 Railway 的问题还是 Panindex 的问题？

这个原因找到了，是因为勾选了`启用防盗链`但是没用勾选`允许空Referrer请求`
