### ISSUE TITLE
挂载GoogleDrive出错

### ISSUE THREAD

**Issue by zhufacai** [libsgh/PanIndex#358]
> 禁止访问：“noki.icu”尚未完成 Google 验证流程
> “noki.icu”尚未完成 Google 验证流程。此应用正在测试中，仅供已获开发者批准的测试人员使用。如果您认为自己应有权使用，请联系开发者。

是我配置有问题吗。。

**Comment by libsgh** [comment]
noki.icu你为什么会用这个地址呢

**Comment by libsgh** [comment]
> > 本工具要求将重定向URI设置为https://pt.noki.icu/
> 
> 我在已获授权的重定向 URI那里填了这个地址= =

好像要把应用上线，明天我写个详细的教程吧。

**Comment by libsgh** [comment]
可以看下这篇图文教程，一步一步来，已经测试通过

https://github.com/libsgh/PanIndex/discussions/359
