### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by erbasisan** [libsgh/PanIndex#364]
# github.com/lib/pq
../go/pkg/mod/github.com/lib/pq@v1.10.2/user_posix.go:13:6: userCurrent redeclared in this block
        ../go/pkg/mod/github.com/lib/pq@v1.10.2/user_other.go:7:6: other declaration of userCurrent
这是啥意思

**Comment by libsgh** [comment]
什么平台？哪个版本？

**Comment by libsgh** [comment]
看你的日志应该是数据库连接方面的问题，如果还未解决的话再打开此issue
