### ISSUE TITLE
建议把页面改为局部刷新形式，这样访问起来会快一些。

### ISSUE THREAD

**Issue by hhun** [libsgh/PanIndex#366]
建议把页面改为`Pjax局部刷新`或者`获取JSON格式数据`的形式，这样访问起来会快一些。
每次点击文件夹都会跳转页面，用户体验不大好，而且访问速度慢。

**Comment by libsgh** [comment]
计划用vue3+vuetify重写md主题，最终的效果应该和pjax一样，就不开新坑了
