### ISSUE TITLE
debug：artplayer跨域的问题

### ISSUE THREAD

**Issue by iocoeoqq** [libsgh/PanIndex#378]
有几个视频，把地址复制到博客或者其他地方播放是可以的，列表程序无法播放，f12提示
`has been blocked by CORS policy: No 'Access-Control-Allow-Origin`后面找了播放器作者，删了这个就行了
/static/js/mdui.video.js
![3](https://user-images.githubusercontent.com/85924444/204945692-680ff006-3d23-4e6d-bd55-ecd2da1dbd02.png)

delete：` moreVideoAttr: {
        crossOrigin: 'anonymous',
    },`

**Comment by libsgh** [comment]
列表程序无法播放的视频链接能给一个吗

**Comment by iocoeoqq** [comment]
不是删除整个js ，/static/js/mdui.video.js，删除这个js里面中的` moreVideoAttr: { crossOrigin: 'anonymous', },`，你试下删除了，f12就不提示这个了

**Comment by libsgh** [comment]
奇怪我这里是没有跨域错误的，你用隐私模式打开试试
![image](https://user-images.githubusercontent.com/25656088/204949261-3af99b7d-fc5e-4d8b-831b-efc4b2f062f5.png)

**Comment by iocoeoqq** [comment]
有了 复现了，隐私模式
![5](https://user-images.githubusercontent.com/85924444/204949796-089b04e7-dd9b-46dd-8691-ee7bf8edd503.png)
