### ISSUE TITLE
请问每点开一个页面就显示这个是什么问题？

### ISSUE THREAD

**Issue by ssln5014** [libsgh/PanIndex#379]
部署在replit，2h3g，配置应该够，是不是主题的问题？
![image](https://user-images.githubusercontent.com/81206855/205242797-8780a869-1dc2-4890-a767-0a0586420af5.png)

**Comment by libsgh** [comment]
抓包看下是不是字体加载失败了，是v3.1.1吗

**Comment by ssln5014** [comment]
> 

版本是最新版，都是大概不到一秒钟就恢复正常了。
demo也一样，应该是字体加载速度太慢
![image](https://user-images.githubusercontent.com/81206855/205244199-a83f68f1-7a82-4df8-8dcd-d4db183c3d71.png)

**Comment by libsgh** [comment]
> > 
> 
> 版本是最新版，都是大概不到一秒钟就恢复正常了。 demo也一样，应该是字体加载速度太慢 ![image](https://user-images.githubusercontent.com/81206855/205244199-a83f68f1-7a82-4df8-8dcd-d4db183c3d71.png)

是的 因为cdn经常失效我就吧字体文件引用到本地了 ，这就取决于服务器速度了

**Comment by libsgh** [comment]
试试最新的开发版本
https://nightly.link/libsgh/PanIndex/workflows/nightly-build/dev
