### ISSUE TITLE
heroku部署出现Application error

### ISSUE THREAD

**Issue by huxxx123** [libsgh/PanIndex#38]
不填写配置文件不会出现Application error，但是没有密码进入系统配置界面

配置文件填写如下
{
    "port": 8080,
    "mode": "cloud189",
    "user": "xxx",
    "password": "xxx",
    "root_id": "-11",
    "heroku_app_url":"https://xxx.herokuapp.com",
    "theme": "classic",
    "cron_exps": {
        "refresh_cookie": "0 0 8 1/1 * ?",
        "update_folder_cache": "0 0 0/1 * * ?",
        "heroku_keep_alive": "0 0/5 * * * ?"
    }
}

**Comment by libsgh** [comment]
2.0.0，先不要设置环境变量，配置好后在系统配置页面 复制配置json，这时再去heroku后台创建

**Comment by huxxx123** [comment]
> 2.0.0，先不要设置环境变量，配置好后在系统配置页面 复制配置json，这时再去heroku后台创建

不设置环境变量进去提示需要密码
![image](https://user-images.githubusercontent.com/52876220/120616819-1e6f2c80-c48c-11eb-9fab-b694e1e3aa89.png)

**Comment by libsgh** [comment]
> > 2.0.0，先不要设置环境变量，配置好后在系统配置页面 复制配置json，这时再去heroku后台创建
> 
> 不设置环境变量进去提示需要密码
> ![image](https://user-images.githubusercontent.com/52876220/120616819-1e6f2c80-c48c-11eb-9fab-b694e1e3aa89.png)

默认密码：`PanIndex`，2.0文档我今天争取传上去 基本上写的差不多了

**Comment by huxxx123** [comment]
> > > 2.0.0，先不要设置环境变量，配置好后在系统配置页面 复制配置json，这时再去heroku后台创建
> > 
> > 
> > 不设置环境变量进去提示需要密码
> > ![image](https://user-images.githubusercontent.com/52876220/120616819-1e6f2c80-c48c-11eb-9fab-b694e1e3aa89.png)
> 
> 默认密码：`PanIndex`，2.0文档我今天争取传上去 基本上写的差不多了

好的，谢谢
