### ISSUE TITLE
PanIndex Tool 第七步获取微软Token，后端API出错

### ISSUE THREAD

**Issue by jstar0** [libsgh/PanIndex#380]
在使用您的 [PanIndex Tool](https://pt.noki.icu/) 时，运行到 *7. 获取TOKEN* ，最新版chrome浏览器报错：

https://api.noki.top/pan/onedrive/exchangeToken 给予了 `ERROR_FAILED 503`
同时有`Access to XMLHttpRequest at 'https://api.noki.top/pan/onedrive/exchangeToken' from origin 'https://pt.noki.icu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

尝试关闭chrome的防跨域保护后，依然报错（503）。

是否有其他替代方案，以获取OneDrive Token。

**Comment by libsgh** [comment]
是因为api部署到heroku上，忘记迁移了...
