### ISSUE TITLE
加入CDN后是否对网盘挂载列表的新增出现问题？

### ISSUE THREAD

**Issue by ysn2382617094wsw** [libsgh/PanIndex#381]
加入CDN后是否对网盘挂载列表的新增出现问题？
没有使用CDN前，每挂载一个网盘都会在“已挂载网盘”列表显示，这很正常，但是加入CDN后，挂载网盘后，“已挂载网盘”中没有新挂载网盘的选项，重启服务，重新登录，刷新缓存都没有作用，很奇怪

**Comment by libsgh** [comment]
你说的加入cdn是什么意思
