### ISSUE TITLE
本地磁盘映射路径是什么

### ISSUE THREAD

**Issue by tingyue-wu** [libsgh/PanIndex#388]
因为不映射出来，感觉管理不方便，只能在上传文件里一个个上传不能把nas现有文件夹直接映射进去。
还有webdav开启后，电脑上链接webdav，是可以查看到panindex挂载的所有盘吗，还是只能看到“本地磁盘”里的文件？

**Comment by libsgh** [comment]
1. 本地目录的绝对路径，你的nas可以开启webdav的花，可以挂载webdav
2. 开启webdav是可以看到所有挂载盘的
