### ISSUE TITLE
阿里云盘资源全部404

### ISSUE THREAD

**Issue by A8Chann** [libsgh/PanIndex#394]
应该是阿里云改了资源获取策略

**Comment by LecoLu** [comment]
+1

**Comment by LecoLu** [comment]
@libsgh

**Comment by libsgh** [comment]
阿里云官方正在推出OpenApi，目前没有公测，功能也没有完善。虽然接口突然噶了，但是毕竟不是官方推荐的方式。
![image](https://user-images.githubusercontent.com/25656088/218701772-3885e889-3091-4166-b4a2-a33edf2aa95f.png)
我已经解析出最新的签名算法，但是考虑到官方对三方客户端的封杀，并没有公布在代码里，而是提供三方接口的方式调用。这只是一种过渡方案，后面会依据情况进行策略调整，最终的方向当然是使用官方承认的API

**请尝试更新到dev最新版本**

**Comment by wangzichenglong** [comment]
> 
> > 2023-02-14 19:42  网上已经有人把算法发出来了，也就不藏着掖着了，这两天顺便发布release版本。

请问release版会把office文档预览功能处理成先转换再预览，进而支持在局域网内也可预览吗？或者已经添加oneoffice的预览服务？

**Comment by libsgh** [comment]
> > > 2023-02-14 19:42  网上已经有人把算法发出来了，也就不藏着掖着了，这两天顺便发布release版本。
> 
> 请问release版会把office文档预览功能处理成先转换再预览，进而支持在局域网内也可预览吗？或者已经添加oneoffice的预览服务？

还没有，先解决紧急问题，已经在研究oneoffice

**Comment by LecoLu** [comment]
> ![image](https://user-images.githubusercontent.com/25656088/218701772-3885e889-3091-4166-b4a2-a33edf2aa95f.png) 阿里云官方正在推出OpenApi，目前没有公测，功能也没有完善。虽然接口突然噶了，但是毕竟不是官方推荐的方式。 我已经解析出最新的签名算法，但是考虑到官方对三方客户端的封杀，并没有公布在代码里，而是提供三方接口的方式调用。这只是一种过渡方案，后面会依据情况进行策略调整，最终的方向当然是使用官方承认的API。
> 
> **请尝试更新到dev最新版本，以解决文件详情404的问题**
> 
> > 2023-02-14 19:42  网上已经有人把算法发出来了，也就不藏着掖着了，这两天顺便发布release版本。

老大，新版要自己编译呀？

**Comment by libsgh** [comment]
> > ![image](https://user-images.githubusercontent.com/25656088/218701772-3885e889-3091-4166-b4a2-a33edf2aa95f.png) 阿里云官方正在推出OpenApi，目前没有公测，功能也没有完善。虽然接口突然噶了，但是毕竟不是官方推荐的方式。 我已经解析出最新的签名算法，但是考虑到官方对三方客户端的封杀，并没有公布在代码里，而是提供三方接口的方式调用。这只是一种过渡方案，后面会依据情况进行策略调整，最终的方向当然是使用官方承认的API。
> > **请尝试更新到dev最新版本，以解决文件详情404的问题**
> > > 2023-02-14 19:42  网上已经有人把算法发出来了，也就不藏着掖着了，这两天顺便发布release版本。
> 
> 老大，新版要自己编译呀？

不需要的，dev分支的代码只要提交代码就会自动构建版本的，在[nightly](https://nightly.link/libsgh/PanIndex/workflows/nightly-build/dev)处下载，docker用dev标签

Release也已经发布了，等构建完直接用Release版本吧
