### ISSUE TITLE
Docker拉取镜像是总是失败

### ISSUE THREAD

**Issue by helloweizhang** [libsgh/PanIndex#398]
错误信息
Trying to pull repository docker.io/iicm/pan-index ... 
manifest for docker.io/iicm/pan-index:v3.1.2 not found

**Comment by helloweizhang** [comment]
Trying to pull repository docker.io/iicm/pan-index ... 
manifest for docker.io/iicm/pan-index:latest not found

**Comment by libsgh** [comment]
镜像仓库是否用了cdn， 官方仓库是有的
https://hub.docker.com/layers/iicm/pan-index/v3.1.2/images/sha256-954045da7f4c263503bca2310286bb168f40cdef669444adae8105b604292558?context=explore

**Comment by helloweizhang** [comment]
直接用教程的命令拉取的. 并且上官方仓库拉取也出错
https://docs.noki.icu/#/quickstart?id=docker

**Comment by libsgh** [comment]
> 直接用教程的命令拉取的. 并且上官方仓库拉取也出错 https://docs.noki.icu/#/quickstart?id=docker

检查你自己的Docker环境，我这里测试是拉取成功的。
![image](https://user-images.githubusercontent.com/25656088/220036963-c3eb93dd-d31e-46e1-86eb-106dbc819f9c.png)

**Comment by libsgh** [comment]
https://hub.docker.com/r/iicm/pan-index/tags
