### ISSUE TITLE
Heroku：后台配置好后，获取配置json，并复制到heroku新的环境变量PAN_INDEX_CONFIG中，端口号会根据环境变量$PORT覆盖，无需关注

### ISSUE THREAD

**Issue by vipy800** [libsgh/PanIndex#43]
Heroku：后台配置好后，获取配置json，并复制到heroku新的环境变量PAN_INDEX_CONFIG中，端口号会根据环境变量$PORT覆盖，无需关注

这个是什么意思，搞不懂，能指点一下吗，或者能出个视频教程吗，宝塔搭建

**Comment by libsgh** [comment]
如果heroku上部署需要注意的，如果是vps这个不用看。

**Comment by vipy800** [comment]
我后台账号配置好了，但是前台不显示内容，不知道是哪里没设置对，能帮我看看吗。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 上午10:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [libsgh/PanIndex] Heroku：后台配置好后，获取配置json，并复制到heroku新的环境变量PAN_INDEX_CONFIG中，端口号会根据环境变量$PORT覆盖，无需关注 (#43)





 
如果heroku上部署需要注意的，如果是vps这个不用看。

**Comment by libsgh** [comment]
你加一下tg群

**Comment by vipy800** [comment]
群链接能给一下吗&nbsp;github里没找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 中午12:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [libsgh/PanIndex] Heroku：后台配置好后，获取配置json，并复制到heroku新的环境变量PAN_INDEX_CONFIG中，端口号会根据环境变量$PORT覆盖，无需关注 (#43)





 
你加一下tg群
 
&mdash;

**Comment by libsgh** [comment]
> 群链接能给一下吗&nbsp;github里没找到
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月9日(星期三) 中午12:13 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [libsgh/PanIndex] Heroku：后台配置好后，获取配置json，并复制到heroku新的环境变量PAN_INDEX_CONFIG中，端口号会根据环境变量$PORT覆盖，无需关注 (#43) 你加一下tg群 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

https://t.me/PanIndex
