### ISSUE TITLE
使用webdav方式挂载了alist时遇到了下载文件404错误

### ISSUE THREAD

**Issue by ghostWindows-files** [libsgh/PanIndex#438]
首先在这里由衷的感谢诸如panindex、alist等网盘的无私的开发者，前人栽树后人乘凉非常感谢
我是从alist过来的，想说就是用webdav挂载ALIST访问结果很多网盘设置看不懂官方文档看了我也是一脸懵逼。
主要是想问一下设置里的流量中转如何配置（是否能通过cloudflare中转流量）
其次我遇到了一个问题，用webdav方式挂在完alist后下载任何文件都提示404，就很绷不住
希望开发者看到帮我解答一下吧，谢谢

**Comment by libsgh** [comment]
1. 可以通过cf中转，中转的原理其实就是在原来下载直链的地址上前面拼接上cf的代理下载地址
2. 需要通过日志看下访问alist的下载地址是什么，是否是有效的下载地址

**Comment by ghostWindows-files** [comment]
> 1. 可以通过cf中转，中转的原理其实就是在原来下载直链的地址上前面拼接上cf的代理下载地址
> 2. 需要通过日志看下访问alist的下载地址是什么，是否是有效的下载地址

谢谢帮助。404的问题现已解决
