### ISSUE TITLE
如何让Panindex连接远程MySQL数据库？

### ISSUE THREAD

**Issue by ghostWindows-files** [libsgh/PanIndex#439]
非常感谢作者开发这样好的软件
如题，请问如何修改配置文件或启动参数让Panindex连接远程MySQL数据库？
有部分serverless服务商不保留数据的重置，因此远程数据库尤其重要这才有此Issues。Panindex说明文档中写了
# postgres
host=localhost user=postgres password=1234 dbname=pan-index port=5432 sslmode=disable TimeZone=Asia/Shanghai
# mysql
user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
# sqlite
data.data.db

请问这是要修改启动参数亦或是配置文件，求教

**Comment by libsgh** [comment]
-c=config.json中dsn参数，或是环境变量根据你的环境而定

**Comment by ghostWindows-files** [comment]
> -c=config.json中dsn参数，或是环境变量根据你的环境而定

非常感谢，刚看了几篇教程。原来要转换成数据库链接形式的
