### ISSUE TITLE
一段时间后目录缓存停止刷新

### ISSUE THREAD

**Issue by Cicini** [libsgh/PanIndex#44]
似乎过一段时间设置的定时任务就不会刷新了
本来设置的30分钟一次
结果几个小时后都没有刷新目录
并且在手动改刷新时间并重启尝试刷新后出现了目录重复的情况(同一个目录在列表中显示多个)

其他:
新版本的手动API似乎没用了(只试了目录刷新没反应)
没有找到MYSQL连接的设置

配置:
teambition (网盘)
源码部署(2.0)
环境debian 10 64x

没有找到本地问题(

**Comment by libsgh** [comment]
1. 应该是某次缓存有失败的情况，异常没有完全处理，如果有异常日志可以帖一下，另外控制刷新缓存的频率，不建议太频繁
2. 数据库使用了sqlite，好处是不用安装数据库，数据库文件在data目录下
3. 之前的手动api已经，废弃了，因为无法指定刷新账号进行刷新，现在是多个账号了，而且有对应按钮

回头我频繁刷新复现一下问题

**Comment by Cicini** [comment]
> 1. 应该是某次缓存有失败的情况，异常没有完全处理，如果有异常日志可以帖一下，另外控制刷新缓存的频率，不建议太频繁
> 2. 数据库使用了sqlite，好处是不用安装数据库，数据库文件在data目录下
> 3. 之前的手动api已经，废弃了，因为无法指定刷新账号进行刷新，现在是多个账号了，而且有对应按钮
> 
> 回头我频繁刷新复现一下问题

蛮奇怪的，我这边没有任何异常日志(甚至连刷新缓存的字样都没有)
还在看是哪块的问题(

**Comment by Cicini** [comment]
测试了一下
在首次配置的时候
配置完成后如果立刻重启(为了完成端口更改等)
重启后缓存会卡住

如果等第一次缓存成功后再重启似乎就没有什么问题

**Comment by libsgh** [comment]
嗯，添加账号后会自动同步cookie和目录缓存，后面我加个提示

**Comment by Cicini** [comment]
> 嗯，添加账号后会自动同步cookie和目录缓存，后面我加个提示

确实可以提醒一下等待缓存结束
以及后面手动缓存的时候也可以加个等待缓存结束的提示
