### ISSUE TITLE
PanIndex在x86_64的Linux系统下运行时报错

### ISSUE THREAD

**Issue by ghostWindows-files** [libsgh/PanIndex#440]
###运行环境
System bit count: x86_64
CPU bit count: 64
###启动参数
./PanIndex-linux-amd64 -c=config.json -reset_password=$AdministratorPwd -reset_user=$AdministratorUserName &
###系统日志
 ____   __    _  _  ____  _  _  ____  ____  _  _ 
(  _ \ /__\  ( \( )(_  _)( \( )(  _ \( ___)( \/ )
 )___//(__)\  )  (  _)(_  )  (  )(_) ))__)  )  ( 
(__) (__)(__)(_)\_)(____)(_)\_)(____/(____)(_/\_)

INFO[2024-07-02 16:08:32] Git Commit Hash:                              function=PrintVersion line=191
INFO[2024-07-02 16:08:32] Version:                                      function=PrintVersion line=192
INFO[2024-07-02 16:08:32] Go Version:                                   function=PrintVersion line=193
INFO[2024-07-02 16:08:32] Build TimeStamp:                              function=PrintVersion line=194
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe63774]

goroutine 1 [running]:
github.com/px-org/PanIndex/boot.InitDb({{0xc000538568, 0x7}, 0x1476, {0xc000538570, 0x4}, {0xc000538770, 0xf}, {0x0, 0x0}, {0x0, ...}, ...})
	/source/boot/boot.go:105 +0xf4
github.com/px-org/PanIndex/boot.Init()
	/source/boot/boot.go:45 +0x218
main.main()
	/source/main.go:31 +0x58

**Comment by libsgh** [comment]
-cq=admin_password 查看一下呢，有很多日志的话看下最后一行

**Comment by ghostWindows-files** [comment]
> -cq=admin_password 查看一下呢，有很多日志的话看下最后一行

很奇怪
上午在huggingface运行的好好的，下午就报上面错。我估计二进制文件被和谐了
大佬，请问有什么好的解决方案吗

**Comment by ghostWindows-files** [comment]
> -cq=admin_password 查看一下呢，有很多日志的话看下最后一行


大佬，请您帮我看一下是我的仓库哪里的问题，现在还是报错
[PanIndex - HuggingFace](https://huggingface.co/spaces/tinapersonal/models/tree/main)


> `===== Application Startup at 2024-07-02 11:17:05 =====
> 
> System bit count: x86_64
> CPU bit count: 64
> 7 120749.json
> Dockerfile
> README.md
> config.json
> configtest.json
> entrypoint.sh
> panindex
> 等待 PanIndex 服务启动...
> 
>  ____   __    _  _  ____  _  _  ____  ____  _  _ 
> (  _ \ /__\  ( \( )(_  _)( \( )(  _ \( ___)( \/ )
>  )___//(__)\  )  (  _)(_  )  (  )(_) ))__)  )  ( 
> (__) (__)(__)(_)\_)(____)(_)\_)(____/(____)(_/\_)
> 
> INFO[2024-07-02 19:17:08] Git Commit Hash:                              function=PrintVersion line=191
> INFO[2024-07-02 19:17:08] Version:                                      function=PrintVersion line=192
> INFO[2024-07-02 19:17:08] Go Version:                                   function=PrintVersion line=193
> INFO[2024-07-02 19:17:08] Build TimeStamp:                              function=PrintVersion line=194
> ERRO[2024-07-02 19:17:08] failed to initialize database, got error [default addr for network '/folderpanindex/data' unknown]  function=Error line=39
> panic: Got error when connect database, the error is 'default addr for network '/folderpanindex/data' unknown'
> 
> goroutine 1 [running]:
> github.com/px-org/PanIndex/dao.Mysql.CreateDb({}, {0xc00010e920, 0x1c})
> 	/source/dao/mysql.go:26 +0x265
> github.com/px-org/PanIndex/boot.InitDb({{0xc0004ce948, 0x7}, 0x1476, {0xc0004ce9a0, 0x4}, {0xc000041860, 0x14}, {0x0, 0x0}, {0x0, ...}, ...})
> 	/source/boot/boot.go:105 +0x108
> github.com/px-org/PanIndex/boot.Init()
> 	/source/boot/boot.go:45 +0x218
> main.main()
> 	/source/main.go:31 +0x58`

**Comment by ghostWindows-files** [comment]
> -cq=admin_password 查看一下呢，有很多日志的话看下最后一行

我服了，又重新摸索了一遍发现原来是环境变量的锅，我把dbtapy填成mysql了
