### ISSUE TITLE
安装完成后，本地的正常，但其他的存储方式，都是提示【状态： 缓存失败】，且都没有内容，后台上传提示成功但实际也无内容，请问下是怎么回事

### ISSUE THREAD

**Issue by 508044570** [libsgh/PanIndex#45]
安装完成后，本地的正常，但其他的存储方式，都是提示【状态： 缓存失败】，且都没有内容，后台上传提示成功但实际也无内容，请问下是怎么回事

![image](https://user-images.githubusercontent.com/20151745/121787172-34e95680-cbf7-11eb-8f3c-fe3dd178b726.png)
![image](https://user-images.githubusercontent.com/20151745/121787199-55191580-cbf7-11eb-8516-f54a281c43b9.png)

**Comment by libsgh** [comment]
用户名密码正确吗，能否帖一下日志

**Comment by 508044570** [comment]
> 用户名密码正确吗，能否帖一下日志

用户名密码是正确的，已经提示登录成功

![image](https://user-images.githubusercontent.com/20151745/121792491-ff109600-cc27-11eb-8634-af93a0845686.png)

**Comment by libsgh** [comment]
手动同步目录缓存，然后再看下日志是否有刷新成功的信息

**Comment by 508044570** [comment]
> 手动同步目录缓存，然后再看下日志是否有刷新成功的信息

已经刷新缓存，但日志没有提示成功的信息

**Comment by libsgh** [comment]
可以设置`-debug=false`,输出更详细的日志，在文档中有联系方式，来反馈吧

**Comment by 508044570** [comment]
解决了，，，是根目录id的问题，没有设置正确，文档那边感觉有点乱，我还以为是填路径"/"，找了半天在1.0文档那边才看到了天翼网盘id，才发现问题

**Comment by libsgh** [comment]
文档做了更新，2.0在常见问题里
