### ISSUE TITLE
刷新缓存失败

### ISSUE THREAD

**Issue by 1170761233** [libsgh/PanIndex#46]
![image](https://user-images.githubusercontent.com/62597175/122133535-77b56380-ce6f-11eb-9a81-07830aa8a851.png)
无法刷新缓存，手动刷新也无法解决  请问这种情况该怎么办，谢谢

**Comment by libsgh** [comment]
请检查，用户名，密码，根目录id设置是否正确

**Comment by 1170761233** [comment]
已经解决了，谢谢
