### ISSUE TITLE
阿里云网盘无法缓存主目录。网站如何一站多盘？

### ISSUE THREAD

**Issue by mymine** [libsgh/PanIndex#49]
阿里云网盘无法缓存主目录。主目录没有ID，填写index和drive都缓存失败，可不可以添加下主目录缓存。

**Comment by libsgh** [comment]
主目录的id是`root`，文档里面我会更新一下，目前已经支持多账号绑定，直接在账号管理那里添加账号即可

**Comment by mymine** [comment]
哦，我换了一个主题，发现了，切换网盘地址，默认主题没法快捷切换网盘。可以修复一下吗？

**Comment by mymine** [comment]
啊，无法切换网盘原来浏览器缓存的问题

**Comment by mymine** [comment]
好啦，设置成root已经成功缓存了。无法快捷切换网盘，是浏览器缓存的问题！OK，所有的问题已经解决了

**Comment by libsgh** [comment]
> 好啦，设置成root已经成功缓存了。无法快捷切换网盘，是浏览器缓存的问题！
> 那个后台上传文件是只支持本地盘上传吗？上面写着要填上传的路径，我填root提示没有该目录！是我在root目录运行程序的问题吗！

你应该填写`/`这里是网盘里的路径，就是相对的了 也就是你访PanIndex的网址后面的路径部分
