### ISSUE TITLE
部署到heroku上，报错

### ISSUE THREAD

**Issue by fengyiyi** [libsgh/PanIndex#5]
`{
    "port": 8080,
    "user": "183xxxx7765",
    "password": "xxxx",
    "root_id": "-11",
    "pwd_dir_id": [
        {
            "id": "51496311321353335",
            "pwd": "1234"
        }
    ],
    "hide_file_id": "",
    "heroku_app_url":"https://pan-index.herokuapp.com"
}`
user password都填写正确，app-url也无误，但还是打不开
`2020-11-23T08:54:42.665652+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-11-23T08:54:42.684998+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-11-23T08:54:42.771712+00:00 heroku[web.1]: Process exited with status 137
2020-11-23T08:54:42.806970+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by libsgh** [comment]
刚我部署了一下，没有问题，你使用的是最新代码吗？heroku程序会有一个`PORT`的环境变量，这个端口号是动态的，我再获取配置的时候做了优先级，优先从环境变量中读取，所以`CONFIG`中的端口号就不会生效。

**Comment by libsgh** [comment]
还有问题请再打开
