### ISSUE TITLE
设置密码方面

### ISSUE THREAD

**Issue by 1170761233** [libsgh/PanIndex#50]
您好，打扰一下
![image](https://user-images.githubusercontent.com/62597175/122523378-89526300-d049-11eb-809a-eef9bdecada8.png)
在设置密码文件夹时ID指的是teambition链接那一串后缀吗？还是指的别的？试了好几次没有成功
比如我设的60cb6f9368cfa3d8a35c40c88d0da65a10165e5a：123   您看是否正确，哪里出了问题？
感谢您在百忙中回复我，谢谢

**Comment by libsgh** [comment]
冒号是半角英文的，检查一下，ID就是链接后面的 应该没问题

**Comment by 1170761233** [comment]
ok 感谢大佬，已经解决了
