### ISSUE TITLE
每天下午打开网址都会显示空白

### ISSUE THREAD

**Issue by 1170761233** [libsgh/PanIndex#52]
每天下午打开网址时都会显示无文件，还要去后台手动刷新缓存
请问是我自己的定时任务设置的有问题还是都这样呢？
<img width="845" alt="image_246" src="https://user-images.githubusercontent.com/62597175/122920295-d14bef80-d393-11eb-94d0-7586ef593fd8.png">

**Comment by libsgh** [comment]
我也有遇到过，应该和heroku强制重启有关系，因为空白后，你去看账号缓存记录是初始化的了，我最近没查到这个机制是多久一次，等有空我查查文档

**Comment by 1170761233** [comment]
> 我也有遇到过，应该和heroku强制重启有关系，因为空白后，你去看账号缓存记录是初始化的了，我最近没查到这个机制是多久一次，等有空我查查文档，你可以先把缓存的任务，调整下执行时间，每四小时执行一次，看看情况

好的，感谢不尽

**Comment by libsgh** [comment]
官方文档如下：
![image](https://user-images.githubusercontent.com/25656088/123016735-d6de1f80-d3fd-11eb-94d2-69d5145ca8bd.png)

原文链接：https://devcenter.heroku.com/articles/sqlite3#disk-backed-storage
