### ISSUE TITLE
用 heroku 部署怎么填 CONFIG？

### ISSUE THREAD

**Issue by hmsjy2017** [libsgh/PanIndex#53]
https://libsgh.github.io/PanIndex/#/README?id=heroku部署
文档中没有详细说明

**Comment by libsgh** [comment]
在[配置](https://libsgh.github.io/PanIndex/#/config?id=%e6%b3%a8%e6%84%8f%e4%ba%8b%e9%a1%b9)中有描述
1. 第一次，config先空着，去后台配置好后，在后台点这个查看config
![image](https://user-images.githubusercontent.com/25656088/123940127-72a5f780-d9cb-11eb-9f29-223db560dd58.png)
2. heroku后台配置，添加config环境变量`PAN_INDEX_CONFIG`

实际使用过程中heroku会强制重启，哪怕开启了防休眠也无效，这种方式对于阿里云和onedrive，在重启后会导致`refresh_token`失效，后面可能会考虑将配置存到postgres中，这样可以进行更新。尽管如此，heroku调用各类网盘的接口还是有点慢的，体验不是很好。如果有条件尽量使用vps部署。
