### ISSUE TITLE
可否支持m3u8

### ISSUE THREAD

**Issue by nfyb** [libsgh/PanIndex#54]

**Comment by libsgh** [comment]
m3u8里面的切片信息是动态的，你存一个当前的文件 里面的ts过期了你还是播放不了

**Comment by nfyb** [comment]
> m3u8里面的切片信息是动态的，你存一个当前的文件 里面的ts过期了你还是播放不了

是的，但m3u8比较好补，mp4视频ios无法播放，这个有解决方法吗？

**Comment by libsgh** [comment]
可能和视频文件有关，尝试下转码呢

**Comment by nfyb** [comment]
> 可能和视频文件有关，尝试下转码呢
应该是，目前alist  sharelist  PanIndex  都不错，如果可以的话PanIndex加个支持m3u8播放，那就太好了

**Comment by nfyb** [comment]
> 可能和视频文件有关，尝试下转码呢
> PanIndex使用的是原生h5播放器，是可以播放m3u8的，如果你的m3u8文件是hls的应该会有我上面提到的问题，非hls还是可以播放的，如果你的文件播放不了发下地址我看看

http://193.200.130.89:5238/%e5%89%a7%e9%9b%86/Z_%e8%87%b4%e5%91%bd%e5%a5%b3%e4%ba%ba

帮看下，我是在别的站下载的m3u8文件

**Comment by libsgh** [comment]
下个版本会支持
