### ISSUE TITLE
本地文件夹怎么设置密码

### ISSUE THREAD

**Issue by zijingsh** [libsgh/PanIndex#57]
比如d_0里的所有都设置密码  d_0:123456  
这样不行啊   是只有网盘的ID可以设置吗

**Comment by libsgh** [comment]
现在不支持将整个根目录都设置密码 只能是下面的子目录，本地文件夹也是可以设置的，格式/opt:123456，目录id在某些模式下就是文件的路径了，比如 本地模式和onedrive

**Comment by zijingsh** [comment]
好的 本地情况下 mp4格式是否支持预览播放（png可预览）  天翼云盘情况下可以预览播放 但是本地mp4好像不支持  麻烦解答一下 谢谢

**Comment by zijingsh** [comment]
好像还是不可以啊  比如 本地硬盘  /opt:123456  没反应    /opt/Tools:123456 Tools:123456 也没有反应

**Comment by zijingsh** [comment]
目录结构 本地磁盘-tool
                              -share
                               -下载
无论是/opt    /tool   /opt/tool  都不行

**Comment by libsgh** [comment]
1. 你的根目录id是如何设置的？`/tool`？如果是这样那么/tool已经是你的根目录了 这里没办法进行密码设置了，你可以隐藏`/tool`下面的目录，`share`或是`下载`设置方就是 `/tool/share:123456`
2. mp4格式是可以预览的包括本地模式，如果你的mp4不能预览（点击之后直接下载），那应该是你的服务器环境有点问题，无法读取mime，你尝试一下安装`mailcap-2.1.41-2.el7.noarch`这个软件

**Comment by zijingsh** [comment]
感谢密码问题已经解决  还有就是MP4问题暂时未解决

**Comment by libsgh** [comment]
2.0.4正式版的时候会修改下逻辑，以后缀名判断是否可以支持预览。

**Comment by libsgh** [comment]
试试v2.0.4 release版本
