### ISSUE TITLE
目录文件正常显示，但无法加载

### ISSUE THREAD

**Issue by willie91** [libsgh/PanIndex#59]
作者你好，我用docker搭建后，阿里云的目录已经成功显示出来，但是所有文件都无法加载，不知道什么情况，您方便打开网站看下吗？谢谢
https://ad.qaq.ee:6/

**Comment by libsgh** [comment]
Refresh Token要用手机端的，你看下[文档](https://libsgh.github.io/PanIndex/#/config?id=%e8%b4%a6%e5%8f%b7%e7%bb%91%e5%ae%9a)

**Comment by willie91** [comment]
> Refresh Token要用手机端的，你看下[文档](https://libsgh.github.io/PanIndex/#/config?id=%e8%b4%a6%e5%8f%b7%e7%bb%91%e5%ae%9a)

感谢，已经成功了~
