### ISSUE TITLE
出现同名文件，无法下载

### ISSUE THREAD

**Issue by kasuganosoras** [libsgh/PanIndex#6]
如图，在反复删除、清空回收站又上传回去（为了测试自动化脚本）后出现了这样的情况：
![img](https://i.imgur.com/KHCenGr.png)
此时重名的两个文件无法下载，点击下载链接会进入相同的页面

**Comment by libsgh** [comment]
这里下载地址用了路径+名称去匹配，所以同名文件会有点问题，
使用id可以解决这个问题，但是http://xxx.zip这种伪静态的下载地址，看上去会比较友好，先尽量避免在同一目录下出现相同文件名的文件吧，或者你有更好的建议。

**Comment by kasuganosoras** [comment]
问题解决了，通过删除掉缓存的 DB 文件让程序重新获取就行了。建议可以先增加一个 API，调用后让程序强制更新缓存。目前我的刷新缓存方法是通过命令行强制重启 Docker 实现刷新。
