### ISSUE TITLE
Docker 版本无法初始化

### ISSUE THREAD

**Issue by FlintyLemming** [libsgh/PanIndex#60]
部署完毕后，初次登陆显示以下界面（应该是让我设置密码）。但无论输入什么都提示密码错误

![](https://user-images.githubusercontent.com/19165511/124781173-c8534480-df75-11eb-8166-f5834d3669de.png)

把数据库搞出来看了一下，也没有用户信息

![](https://user-images.githubusercontent.com/19165511/124781289-db661480-df75-11eb-9e82-d53edceb6688.png)

**Comment by libsgh** [comment]
后台的密码是保存在`config`表中，默认密码是`PanIndex`

**Comment by FlintyLemming** [comment]
好的好的，谢谢
