### ISSUE TITLE
onedrive获取refreshtoken问题

### ISSUE THREAD

**Issue by xuebiya** [libsgh/PanIndex#63]
怎么获取onedrive的refreshtoken

**Comment by libsgh** [comment]
https://libsgh.github.io/PanIndex/#/config?id=%e8%b4%a6%e5%8f%b7%e7%bb%91%e5%ae%9a

**Comment by xuebiya** [comment]
好的谢谢

**Comment by xuebiya** [comment]
> https://libsgh.github.io/PanIndex/#/config?id=%e8%b4%a6%e5%8f%b7%e7%bb%91%e5%ae%9a

获取时候t1.netrss.cf访问不了

**Comment by libsgh** [comment]
> > https://libsgh.github.io/PanIndex/#/config?id=%e8%b4%a6%e5%8f%b7%e7%bb%91%e5%ae%9a
> 
> 获取时候t1.netrss.cf访问不了

https://t1.netrss.cf 正常用浏览器可以打开吗？打不开的话只能尝试挂下梯子或是在网上找下其他教程

**Comment by xuebiya** [comment]
> > > https://libsgh.github.io/PanIndex/#/config?id=%e8%b4%a6%e5%8f%b7%e7%bb%91%e5%ae%9a
> > 
> > 
> > 获取时候t1.netrss.cf访问不了
> 
> https://t1.netrss.cf 正常用浏览器可以打开吗？打不开的话只能尝试挂下梯子或是在网上找下其他教程

梯子全局都打不开

**Comment by xuebiya** [comment]
> https://blog.imzjw.cn/posts/cf-onedrive/
> 参考下这篇文章，用postman模拟一下请求

获取到目录了，但是目录里面没有显示到文件

**Comment by libsgh** [comment]
> > https://blog.imzjw.cn/posts/cf-onedrive/
> > 参考下这篇文章，用postman模拟一下请求
> 
> 获取到目录了，但是目录里面没有显示到文件

给个截图，根目录设置成`/`，手动同步 再看下同步信息 及日志

**Comment by xuebiya** [comment]
> E

![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了

**Comment by libsgh** [comment]
> > E
> 
> ![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
> 换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了

用了最新版后 重新同步了吗？你的根目录ID怎么设置的？

**Comment by xuebiya** [comment]
> > > E
> > 
> > 
> > ![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
> > 换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了
> 
> 用了最新版后 重新同步了吗？你的根目录ID怎么设置的？

重新同步了，根目录ID设置成/

**Comment by xuebiya** [comment]
> > > > E
> > > 
> > > 
> > > ![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
> > > 换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了
> > 
> > 
> > 用了最新版后 重新同步了吗？你的根目录ID怎么设置的？
> 
> 重新同步了，根目录ID设置成/

![QQ图片20210713225842](https://user-images.githubusercontent.com/58581151/125475102-398bb40c-39c3-4ae9-bbf7-aefd2fb0292a.png)
你看

**Comment by libsgh** [comment]
> > > > > E
> > > > 
> > > > 
> > > > ![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
> > > > 换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了
> > > 
> > > 
> > > 用了最新版后 重新同步了吗？你的根目录ID怎么设置的？
> > 
> > 
> > 重新同步了，根目录ID设置成/
> 
> ![QQ图片20210713225842](https://user-images.githubusercontent.com/58581151/125475102-398bb40c-39c3-4ae9-bbf7-aefd2fb0292a.png)
> 你看

上次改过后没有发版，正在release v2.0.4-BETA4，过会儿更新后再试试吧

**Comment by xuebiya** [comment]
> > > > > > E
> > > > > 
> > > > > 
> > > > > ![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
> > > > > 换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了
> > > > 
> > > > 
> > > > 用了最新版后 重新同步了吗？你的根目录ID怎么设置的？
> > > 
> > > 
> > > 重新同步了，根目录ID设置成/
> > 
> > 
> > ![QQ图片20210713225842](https://user-images.githubusercontent.com/58581151/125475102-398bb40c-39c3-4ae9-bbf7-aefd2fb0292a.png)
> > 你看
> 
> 上次改过后没有发版，正在release v2.0.4-BETA4，过会儿更新后再试试吧

好的

**Comment by xuebiya** [comment]
> > > > > > > E
> > > > > > 
> > > > > > 
> > > > > > ![QQ图片20210713224950](https://user-images.githubusercontent.com/58581151/125473855-958ce9f1-9a09-42de-bfd3-6a9289acfd22.png)
> > > > > > 换上了最新版 还是一样获取不了，在根目录下就能显示文件，目录里面显示不了
> > > > > 
> > > > > 
> > > > > 用了最新版后 重新同步了吗？你的根目录ID怎么设置的？
> > > > 
> > > > 
> > > > 重新同步了，根目录ID设置成/
> > > 
> > > 
> > > ![QQ图片20210713225842](https://user-images.githubusercontent.com/58581151/125475102-398bb40c-39c3-4ae9-bbf7-aefd2fb0292a.png)
> > > 你看
> > 
> > 
> > 上次改过后没有发版，正在release v2.0.4-BETA4，过会儿更新后再试试吧
> 
> 好的

可以了，已经获取到了，谢谢
