### ISSUE TITLE
近期程序开发计划讨论

### ISSUE THREAD

**Issue by libsgh** [libsgh/PanIndex#7]
-  ~~添加一些api接口，如 分享链接直链解析（下个版本移除，迁移到私人项目中）~~
- 后台管理：增加详细的配置，例如缓存定时任务，手动同步，上传文件（优先级低）
- ~~图床：天翼云网盘的空间不大，感觉用来做图床不太合适。~~
- 主题已有classic, bootstrap（by [kasuganosoras](https://github.com/kasuganosoras)）, materialdesign (by [kasuganosoras](https://github.com/kasuganosoras))，功能比较简单，预览只支持视频、图片和office。高级主题（优先级中）
- 添加对teambition网盘的支持、本地模式（优先级高）

大家有好的建议也可以参加讨论，目前PanIndex的定位是简洁，实用，高效。

**Comment by kasuganosoras** [comment]
0）其实目前分享功能基本上用不到……下载链接基本都可以无需认证访问
1）建议实现前后端分离，后端只是单纯提供 API 服务，具体界面之类的由静态前端来完成比较好
2）15GB 做图床的话我感觉我能用一年……
3）两种主题已经完成啦~已提 Pr
4）阿里云盘我这边已经申请到内测用户资格了，如果有需要的话可以一起研究下

**Comment by libsgh** [comment]
> 0）其实目前分享功能基本上用不到……下载链接基本都可以无需认证访问
> 1）建议实现前后端分离，后端只是单纯提供 API 服务，具体界面之类的由静态前端来完成比较好
> 2）15GB 做图床的话我感觉我能用一年……
> 3）两种主题已经完成啦~已提 Pr
> 4）阿里云盘我这边已经申请到内测用户资格了，如果有需要的话可以一起研究下

- 一下午搞了个分享直链的api，我其实也没这方面需求，但是其他人有。可以搞个静态页面，配合api做个解析站
- 因为前端代码比较少，如果不做后台的话基本也不需要什么接口，而且前后端分离对于部署复杂了些，这里打到一个包里方便点。
- 15G自用只存图片还好，要是还放其他东西就...
- 你这太效率了，膜拜大佬，非常感谢pr
- 阿里云现在搞了两个云盘，具体的使用情况，上线还要再观望一下，阿里云盘还没上线网页版
验证码登录的问题：我在开发的时候偶尔能遇到，天翼云的登录接口还是很稳定的，控制好频率几乎不会出现验证码，cookie也不会掉，当时就犯懒了

加下q：359916450，有空一起研究交流交流

**Comment by y377** [comment]
这玩意我的建议是解决“小众人的痛点”；所谓树大招风，你硬是给他做成小白都能用，大家都来占用“翼盘”，我想Chinanet不会放任不管的。到时候给你来一套什么“破坏计算机软件系统安全罪等”。
   老一些的电信用户，比如我有2T空间，是可以做成公共网盘，存一下Linux、Windows的iso安装包等，供大家用，图床功能我建议开通，但是仅限于自己用自己的账号上传，可公开访问，万一有人上传了违规违法图片，顺着网线网上查，“翼盘”账号所有者，程序提供者都脱不了干系

**Comment by libsgh** [comment]
> 这玩意我的建议是解决“小众人的痛点”；所谓树大招风，你硬是给他做成小白都能用，大家都来占用“翼盘”，我想Chinanet不会放任不管的。到时候给你来一套什么“破坏计算机软件系统安全罪等”。
> 老一些的电信用户，比如我有2T空间，是可以做成公共网盘，存一下Linux、Windows的iso安装包等，供大家用，图床功能我建议开通，但是仅限于自己用自己的账号上传，可公开访问，万一有人上传了违规违法图片，顺着网线网上查，“翼盘”账号所有者，程序提供者都脱不了干系

有一定道理，我做这个的初衷就是分享自己的网盘文件，主要是自用，也不想做的太复杂，不会做公共图床的功能。

**Comment by y377** [comment]
你这个要是能和cloud189-go无缝衔接那就完美了，我有空试下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;libsgh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月22日(星期五) 上午10:02
收件人:&nbsp;&quot;libsgh/PanIndex&quot;<PanIndex@noreply.github.com&gt;;
抄送:&nbsp;&quot;y377&quot;<csever@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [libsgh/PanIndex] 近期程序开发计划讨论 (#7)

**Comment by y377** [comment]
你的程序和[cloudpan189-go](https://github.com/tickstep/cloudpan189-go). 无缝组合就完美了
[Duck Duck Go](https://duckduckgo.com)奇怪了，Github MD语法超链接失效还是我只是不对？
[简书](http://jianshu.com)

**Comment by y377** [comment]
@libsgh 你好，我是centos7，不懂go用法，能否教程再详细点？
这是我目前的状态，也不知道启动了没，腾讯云服务器，以放行相关端口，还是无法访问。
`[root@tx_1 ~]# ls
config.json  data  LICENSE  PanIndex  PanIndex-v1.0.2-linux-amd64.tar.gz  README.md
[root@tx_1 ~]# ./PanIndex -config.path=/root/config.json
2021/01/22 23:00:00 [程序启动]Sqlite数据库 >> 连接成功
flag provided but not defined: -config.path
Usage of ./PanIndex:
  -config string
        配置文件config.json的路径 (default "config.json")
[root@tx_1 ~]#
`
![image](https://user-images.githubusercontent.com/58632405/105507366-0e895400-5d06-11eb-9ee1-d82c3a67b35c.png)

**Comment by YohoYang** [comment]
好棒！感觉可以有个简单的referer防盗链，是否允许空referer以及referer白名单这样的，在向天翼云请求前就可以拦下来，不然怕后面用的人多了，被盗链是其一，还有可能被天翼ban？

**Comment by kasuganosoras** [comment]
> nohup ./PanIndex >out.file 2>&1 & 此执行命令依旧会在24~48小时后出现502，即PanIndex进程没了，正在寻找原因

经过我的监控，发现软件时不时会出现拉取文件列表失败的情况，拉取失败的时候会出现致命错误然后导致程序退出。

解决办法：写个脚本循环执行，当 PanIndex 挂掉的时候自动重启

```sh
#!/bin/sh
while true
do
    ./PanIndex
done
```

推荐使用 screen 软件让 PanIndex 常驻在后台，同时又方便管理

```sh
apt install screen
# or
yum install screen
```

然后

```sh
# start.sh 为上面这个脚本的名字
screen -S panindex ./start.sh
```

**Comment by libsgh** [comment]
> > nohup ./PanIndex >out.file 2>&1 & 此执行命令依旧会在24~48小时后出现502，即PanIndex进程没了，正在寻找原因
> 
> 经过我的监控，发现软件时不时会出现拉取文件列表失败的情况，拉取失败的时候会出现致命错误然后导致程序退出。
> 
> 解决办法：写个脚本循环执行，当 PanIndex 挂掉的时候自动重启
> 
> ```shell
> #!/bin/sh
> while true
> do
>     ./PanIndex
> done
> ```
> 
> 推荐使用 screen 软件让 PanIndex 常驻在后台，同时又方便管理
> 
> ```shell
> apt install screen
> # or
> yum install screen
> ```
> 
> 然后
> 
> ```shell
> # start.sh 为上面这个脚本的名字
> screen -S panindex ./start.sh
> ```

可以使用`Systemd`将PanIdex作为守护进程启动，这里的关键在于获取目录列表产生了什么错误，有没有日志，我的程序部署在heroku上没有出现过这种问题，至于缓存目录任务失败导致gin退出，我要测试看看，推测可能和`robfig/cron`有关

**Comment by y377** [comment]
@kasuganosoras 作者发了我另一个方法，从源代码运行；截止他将“方法”发给我应该快一周了，并未出现掉线（目前我在“藤熏云”运行的），并且我将更改HTML&css,近日因春节在家打扫卫生更改进度耽误，等不忙时我会将改“美”后的源码以及方法发出来。
我的演示[demo](https://www.hupan.vip/)

**Comment by libsgh** [comment]
> 好棒！感觉可以有个简单的referer防盗链，是否允许空referer以及referer白名单这样的，在向天翼云请求前就可以拦下来，不然怕后面用的人多了，被盗链是其一，还有可能被天翼ban？

下个版本加防盗链支持

**Comment by libsgh** [comment]
> cloud189 那个我一直在用，我搞游戏的，写了个脚本自动把我的游戏更新推送到网盘上，配合 PanIndex 做客户端下载分发，速度起飞；另外那个界面我设计的时候就没有想过兼容手机，所以显示不对很正常，可以自己改。

看了下那个api确实很全，我可以移植过来几个上传相关的api，怎么样？

**Comment by YohoYang** [comment]
> > 好棒！感觉可以有个简单的referer防盗链，是否允许空referer以及referer白名单这样的，在向天翼云请求前就可以拦下来，不然怕后面用的人多了，被盗链是其一，还有可能被天翼ban？
> 
> 下个版本加防盗链支持

感谢！！我这两天先自己fork然后改了一些，基本能用，但是不太懂go，设置什么的没加，贴上仅供参考，就不提pull request了

是在main.go的 index方法下面直接加下面的代码块

`

	isForbidden := true
	host := c.Request.Host
	referer, err := url.Parse(c.Request.Referer())
	if err != nil {
		log.Println(err)
	}
	reqFullUrl := host + c.Request.URL.String()

	if referer != nil {
		//如果referer不为空
		if referer.Host == host { //站内referer自动通过免白名单
			isForbidden = false;
		}
		if referer.Host == "www.xxxx.com" { //白名单，如果支持多个可能要改成循环
			isForbidden = false;
		} 
	} else if reqFullUrl == "www.xxxx.com" { //允许直接访问首页，但不允许直接引用文件，首页地址，不太熟悉go不知道怎么获取带https://的完整url，应该可以用config.GloablConfig.HerokuAppUrl
		isForbidden = false;
	} else {
		//空referer
		//if config.GloablConfig.AllowEmptyReferer == true { //是否判断允许空referer可以直接访问，我没加设置所以先注释了
		//	isForbidden = false;
		//}
	}
	
	if isForbidden == true {
		c.String(http.StatusForbidden, "403 Hotlink Forbidden")
		return
	}
`
