### ISSUE TITLE
怎么隐藏目录呀，有实例吗？

### ISSUE THREAD

**Issue by jikeku** [libsgh/PanIndex#75]
请问下 怎么隐藏目录呀，有实例吗？
加密的id1:xxx是什么意思？哪里找到ID

阿里云盘提示这样的错误怎么解决？
This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by libsgh** [comment]
1. 这里的ID是指网盘的文件ID，和根目录ID一样的方式获取，xxx就是你的密码
2. 哪里出现的错误提示，什么操作详细描述一下

**Comment by jikeku** [comment]
哪里出现的错误提示，什么操作详细描述一下
答：阿里网盘填写（Refresh Token）能够获取正常的目录，但是一旦点击（任何）文件下载，就弹出错误

错误截图：https://dd-static.jd.com/ddimg/jfs/t1/182331/7/17006/14528/61056c24E85b72be1/7a7cf68b35018541.png
请问是那部操作问题了吗？

**Comment by libsgh** [comment]
> 哪里出现的错误提示，什么操作详细描述一下
> 答：阿里云盘（Refresh Token）可以获取正常的目录，但是一旦点击（任何）文件下载，就弹出错误
> 
> 错误截图：https://dd-static.jd.com/ddimg/jfs/t1/182331/7/17006/14528/61056c24E85b72be1/7a7cf68b35018541.png
> 请问是那部操作问题了吗？

应该是你的refresh token获取不对，要用手机端的token，按照文档中的教程获取一下
