### ISSUE TITLE
天翼云盘最好的直链系统，没有之一

### ISSUE THREAD

**Issue by beizi1754** [libsgh/PanIndex#76]
用了无数个天翼云盘的直链，这个是最好的。无论文件下载还是音视频演示都无比方便流畅！
如果可以，多给作者捐助一些。给作者更新下去的动力！！

**Comment by libsgh** [comment]
感谢支持，会继续努力😊

**Comment by beizi1754** [comment]
> 感谢

**Comment by beizi1754** [comment]
> 感谢支持，会继续努力😊

咨询下。怎么更新PanIndex呢？简单些的方法

**Comment by libsgh** [comment]
以后会有脚本，目前手动替换重启...或者docker

**Comment by beizi1754** [comment]
> 以后会有脚本，目前手动替换重启...或者docker

收到！
