### ISSUE TITLE
可以出个宝塔面板搭建你这网盘的教程嘛

### ISSUE THREAD

**Issue by HankMo** [libsgh/PanIndex#78]
可以出个宝塔面板搭建你这网盘的教程嘛

**Comment by a2313153** [comment]
在Supervisor下运行不就是宝塔里的教程么

**Comment by HankMo** [comment]
🆗 已经搭建好了  请问底部md文件是怎么显示的

**Comment by libsgh** [comment]
> 🆗 已经搭建好了 请问底部md文件是怎么显示的

放一个`README.md`文件在目录下即可

**Comment by libsgh** [comment]
一些使用问题可以查看文档，或是加群询问
