### ISSUE TITLE
加密文件夹泄露

### ISSUE THREAD

**Issue by Mas0nShi** [libsgh/PanIndex#80]
使用搜索功能可使加密的文件夹被查询到且可被下载
这几乎使得加密文件夹的功能失效~

**Comment by libsgh** [comment]
下版修复此项

**Comment by libsgh** [comment]
已在v2.0.5 release版本解决

**Comment by shelken** [comment]
<img src='https://i.loli.net/2021/08/22/givVL5fpKHU9QEJ.png' alt='givVL5fpKHU9QEJ'/>
2.0.5依然有该问题。

**Comment by shelken** [comment]
重新测试了下，重启后正常了
