### ISSUE TITLE
建议添加pdf在线预览

### ISSUE THREAD

**Issue by YuanFeiY** [libsgh/PanIndex#81]
建议添加pdf在线预览

**Comment by Cicini** [comment]
pdf.... 大部分浏览器本身就支持的吧

**Comment by YuanFeiY** [comment]
> pdf.... 大部分浏览器本身就支持的吧

但是可以预览会更好呀（只是个建议）因为如果pdf比较多在页面点开就能预览会比较方便

**Comment by libsgh** [comment]
之前没支持是因为，下载链接本身不支持，需要做下中转。2.0.5正式发布的时候就会支持了

**Comment by YuanFeiY** [comment]
好的，谢谢
