### ISSUE TITLE
无法载入列表界面

### ISSUE THREAD

**Issue by ysn2382617094wsw** [libsgh/PanIndex#82]
无法载入列表界面，但是管理后台进得去
ERRO[2021-08-06 20:21:53] runtime error: index out of range [0] with length 0  function=func1 line=36
2021/08/06 20:21:53 http: panic serving 127.0.0.1:52282: assignment to entry in nil map
goroutine 86 [running]:
net/http.(*conn).serve.func1(0xc00051a000)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1955f80, 0x1b37d50)
        /usr/local/go/src/runtime/panic.go:971 +0x49a
main.index(0xc0004760f0)
        /github/workspace/main.go:260 +0x2d0
main.main.func1(0xc0004760f0)
        /github/workspace/main.go:154 +0x9a5
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0004760f0)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0x107
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.serveError(0xc0004760f0, 0x194, 0x179fc60, 0x12, 0x12)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 +0x50
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0003ce3c0, 0xc0004760f0)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 +0x51c
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0003ce3c0, 0x1b545b8, 0xc00015a0e0, 0xc00046e200)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x155
net/http.serverHandler.ServeHTTP(0xc00015a000, 0x1b545b8, 0xc00015a0e0, 0xc00046e200)
        /usr/local/go/src/net/http/server.go:2887 +0xaa
net/http.(*conn).serve(0xc00051a000, 0x1b56660, 0xc0003866c0)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x3b8
ERRO[2021-08-06 20:21:53] runtime error: index out of range [0] with length 0  function=func1 line=36
2021/08/06 20:21:53 http: panic serving 127.0.0.1:65252: assignment to entry in nil map
goroutine 87 [running]:
net/http.(*conn).serve.func1(0xc00051a3c0)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1955f80, 0x1b37d50)
        /usr/local/go/src/runtime/panic.go:971 +0x49a
main.index(0xc0004762d0)
        /github/workspace/main.go:260 +0x2d0
main.main.func1(0xc0004762d0)
        /github/workspace/main.go:154 +0x9a5
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0004762d0)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0x107
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.serveError(0xc0004762d0, 0x194, 0x179fc60, 0x12, 0x12)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 +0x50
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0003ce3c0, 0xc0004762d0)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 +0x51c
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0003ce3c0, 0x1b545b8, 0xc00015a1c0, 0xc00046e400)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x155
net/http.serverHandler.ServeHTTP(0xc00015a000, 0x1b545b8, 0xc00015a1c0, 0xc00046e400)
        /usr/local/go/src/net/http/server.go:2887 +0xaa
net/http.(*conn).serve(0xc00051a3c0, 0x1b56660, 0xc000386e80)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x3b8
ERRO[2021-08-06 20:21:53] runtime error: index out of range [0] with length 0  function=func1 line=36
2021/08/06 20:21:53 http: panic serving 127.0.0.1:59723: assignment to entry in nil map
goroutine 31 [running]:
net/http.(*conn).serve.func1(0xc00068a140)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1955f80, 0x1b37d50)
        /usr/local/go/src/runtime/panic.go:971 +0x49a
main.index(0xc0004764b0)
        /github/workspace/main.go:260 +0x2d0
main.main.func1(0xc0004764b0)
        /github/workspace/main.go:154 +0x9a5
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0004764b0)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0x107
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.serveError(0xc0004764b0, 0x194, 0x179fc60, 0x12, 0x12)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 +0x50
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0003ce3c0, 0xc0004764b0)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 +0x51c
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0003ce3c0, 0x1b545b8, 0xc00015a2a0, 0xc000122500)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x155
net/http.serverHandler.ServeHTTP(0xc00015a000, 0x1b545b8, 0xc00015a2a0, 0xc000122500)
        /usr/local/go/src/net/http/server.go:2887 +0xaa
net/http.(*conn).serve(0xc00068a140, 0x1b56660, 0xc0004caac0)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x3b8

**Comment by libsgh** [comment]
请使用最新版
