### ISSUE TITLE
请问怎么设置访问的密码啊

### ISSUE THREAD

**Issue by kennysino** [libsgh/PanIndex#83]
我想把我阿里云的一个文件夹弄过来 
但是我希望访问的时候要有个密码
我的阿里云的id比如说是 6072dfa49cc203284883424f957e93dd175bf88e  假如我想设置访问密码是 1234
我在“基础设置”“密码文件（夹）”那里
我设置6072dfa49cc203284883424f957e93dd175bf88e:1234无效
我设置d_1:1234还是无效
可以告知一下要怎么设置吗？

**Comment by libsgh** [comment]
正常应该用网盘的文件id，`6072dfa49cc203284883424f957e93dd175bf88e `是你的根目录么

**Comment by kennysino** [comment]
我没有明白 我的阿里云盘 根目录下有一个名为“mv”的目录 这个mv在阿里云那里的id是 6072dfa49cc203284883424f957e93dd175bf88e 我想把这个目录加个1234的密码 
请问我该怎么操作呢
如果不知道根目录下的文件夹 那你可否告知正确的设置方法
感谢

**Comment by libsgh** [comment]
> 我没有明白 我的阿里云盘 根目录下有一个名为“mv”的目录 �这个mv在阿里云那里的id是 6072dfa49cc203284883424f957e93dd175bf88e 我想把这个目录加个1234的密码
> 请问我该怎么操作呢
> 如果不知道根目录下的文件夹 那你可否告知正确的设置方法
> 感谢
6072dfa49cc203284883424f957e93dd175bf88e:1234 就可以
