### ISSUE TITLE
一键部署到heroku配置好设置会被重置

### ISSUE THREAD

**Issue by realzsy** [libsgh/PanIndex#84]
昨天尝试一键部署到heroku，很好用，进入后把阿里云盘设置好后能正常访问和下载，过了几个小时再进去就又自动进入后台admin界面，管理密码也被重置成默认panindex这个密码了，然后进去果然之前的配置都没有了。昨天出现了两次这个情况了，是我哪里没弄对吗？

**Comment by libsgh** [comment]
目前PanIndex依赖于本地数据库SQLite，heroku的重置机制会删除配置数据，为了解决这个问题引入了环境变量，将配置好的配置文件，以环境变量的方式设置到heroku，这样就可以保证环境变量不会丢失，**但是这种情况对于阿里云盘这种需要刷新refresh_token的网盘，由于没有办法自动刷新环境变量，目前还还无法解决，建议更换部署方式**
https://github.com/libsgh/PanIndex/issues/52#issuecomment-866431114

**Comment by libsgh** [comment]
> 了解，或者是替换成其他网盘使用吗？

天翼云盘，或者是teambition项目盘
