### ISSUE TITLE
这个是不支持我这款cpu吗

### ISSUE THREAD

**Issue by kennysino** [libsgh/PanIndex#85]
这个panindex在我的群晖上用着还不错
我有另外一款设备 用的是omv的系统
里面也有docker 
我用docker的方式来安装
提示警告
是不支持我这个cpu吗？
麻烦解答一下 感谢了

`Linux wdnas 4.1.17 #9 SMP PREEMPT Mon Jun 29 21:47:06 UTC 2020 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Aug 11 20:06:28 2021 from 192.168.2.172
root@wdnas:~# docker pull iicm/pan-index:latest
latest: Pulling from iicm/pan-index
69692152171a: Pull complete 
c98e1cf6cc9a: Pull complete 
a1c884fd1448: Pull complete 
45957aa1b68c: Pull complete 
7a98ad36740d: Pull complete 
dc525e5485b4: Pull complete 
Digest: sha256:3667c75097f80591c0a4b91eecd60e57324c82454697893ea36e7c7cfe744242
Status: Downloaded newer image for iicm/pan-index:latest
docker.io/iicm/pan-index:latest
root@wdnas:~# docker stop PanIndex
Error response from daemon: No such container: PanIndex
root@wdnas:~# docker rm PanIndex
Error: No such container: PanIndex
root@wdnas:~# docker run -itd \
>  --restart=always \
>  --name PanIndex \
>  -p 5238:5238 \
>  -v /srv/dev-sataa24/users/kenny/docker/PanIndex/data:/app/data \
>  -e PORT="5238" \
>  iicm/pan-index:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
1a9a408f7dce7cb6d437a06592c803e651557e87bc682f83b4e50e261f3ac317
root@wdnas:~# 
`

**Comment by libsgh** [comment]
你用的是什么设备呢？docker是linux/amd64的，如果是arm架构的可以试试这里的程序
https://github.com/libsgh/PanIndex/releases/tag/v2.0.5-BETA2

**Comment by kennysino** [comment]
老大回复很快哦
万分感谢
我的设备是 西部数据的 “my cloud home” 应该是arm的
我现在安装的是omv的系统
我是小白呢
你这个新版的程序要怎么安装
我的是docker
还是可以用上面的命令行吗？

**Comment by kennysino** [comment]
按理说 docker pull iicm/pan-index:latest
这就应该是最新的啊

**Comment by libsgh** [comment]
> 按理说 docker pull iicm/pan-index:latest
> 这就应该是最新的啊

这个docker镜像是linux/amd6的，你可以直接运行编译好的arm架构的程序

**Comment by kennysino** [comment]
大佬大佬
我是小白
用docker安装我还会用
你说的直接运行是怎么操作啊
感谢大佬

**Comment by kennysino** [comment]
感谢 
好像PanIndex-v2.0.5-BETA2-linux-arm64.tar.gz这个可以

**Comment by libsgh** [comment]
> > 按理说 docker pull iicm/pan-index:latest
> > 这就应该是最新的啊
> 
> 这个docker镜像是linux/amd64的，你可以直接运行编译好的arm架构的程序

使用问题可以看文档，不明白的话在文档中找到交流群 加一下。
