### ISSUE TITLE
链接无法被其他IP下网站访问

### ISSUE THREAD

**Issue by T25kevin** [libsgh/PanIndex#87]
链接无法被其他IP下网站访问
>>>>
机器A下做panindex，nginx反向实现域名访问，然后获得域名下播放链接。
>>>>
将机器A下的panindex获取到url，拿到机器B下的网站播放，出现视频加载失败。
>>>>
浏览器可以直接打开URL并下载。但却无法在网站下播放

请问我该如何解决？

**Comment by libsgh** [comment]
除了阿里云盘，其他模式是可以拿来做外链的，除非你在配置里面加了防盗链，或是你在nginx层做了防盗链。
