### ISSUE TITLE
v2.0.5正式版打开网站就需要输入密码

### ISSUE THREAD

**Issue by beizi1754** [libsgh/PanIndex#91]
v2.0.5-BETA2用着一直OK的。更新到v2.0.5正式版后打开网站需要输入密码。可我没有设置任何访问密码哦。。。没办法又还原回v2.0.5-BETA2先用着

**Comment by libsgh** [comment]
已经重新编译发布，请再更新一下

**Comment by boluofan** [comment]
一样 不过我找到了生成的sqllite数据库文件 用工具打开后找到了初始密码 “PanIndex”

**Comment by libsgh** [comment]
> PanIndex

他的问题是前台密码，后台密码默认是PanIndex，这个文档里就有写

**Comment by boluofan** [comment]
2333 好的 我都没看到这个文档 我再去看看
