### ISSUE TITLE
目录id怎么填写？

### ISSUE THREAD

**Issue by boluofan** [libsgh/PanIndex#93]
你好，我看文档上说是阿里云的根目录是 root 目录id是浏览器地址上最后那个值 但账号配置时路径这栏怎么填呢？是这样吗？
![Snipaste_2021-08-16_16-02-25](https://user-images.githubusercontent.com/40459801/129531308-b06bda97-240c-479b-a31a-1cad90878153.png)

**Comment by libsgh** [comment]
意思是说如果你想分享阿里云网盘的根目录的话就填root，如果不是的话 进入到你想分享的目录 地址栏最后面的字符串就是目录id

**Comment by boluofan** [comment]
好的好的 多谢大佬 秒回啊

**Comment by boluofan** [comment]
大佬 不好意 再问下 我这个配置成功了 视频可以加载但是播放黑屏只有音频 这是什么情况呢？还有群号是多少 我可以在群里问问 不用一直麻烦你
![image](https://user-images.githubusercontent.com/40459801/129538950-37c2945d-8e36-4373-8f88-ecb314d6266c.png)

**Comment by libsgh** [comment]
> 大佬 不好意 再问下 我这个配置成功了 视频可以加载但是播放黑屏只有音频 这是什么情况呢？还有群号是多少 我可以在群里问问 不用一直麻烦你
> ![image](https://user-images.githubusercontent.com/40459801/129538950-37c2945d-8e36-4373-8f88-ecb314d6266c.png)

视频文件的问题，h5播放视频浏览器主要支持下面的格式

mp4 = 带有 H.264 视频编码和 AAC 音频编码的 MPEG 4 文件
WebM = 带有 VP8 视频编码和 Vorbis 音频编码的 WebM 文件
Ogg = 带有 Theora 视频编码和 Vorbis 音频编码的 Ogg 文件

mkv有些是黑屏没声音的

https://libsgh.github.io/PanIndex/#/ask

**Comment by boluofan** [comment]
好的 麻烦了

**Comment by boluofan** [comment]
发下群号呢 大佬

**Comment by boluofan** [comment]
不好意思2333 请无视上一条
