### ISSUE TITLE
关于OneDrive如何获取刷新令牌能否出个教程

### ISSUE THREAD

**Issue by a1092595196** [libsgh/PanIndex#95]
在微软azure中应用程序id 密码值 都获取了就是无法获得刷新令牌是否需要设置什么权限？

**Comment by longda33** [comment]
教程：https://imnks.com/2756.html

**Comment by longke233** [comment]
教程：https://imnks.com/2756.html

**Comment by libsgh** [comment]
‘’就是无法刷新令牌‘’，这种描述很难帮助你。按照上面的仔细的再走一遍步骤吧。

**Comment by AlliotTech** [comment]
Authorize for code 这一步确实有问题。。。点击Authorize 后，页面只是刷新了，没有返回
