### ISSUE TITLE
阿里云盘可以获取到目录，但是无法预览和下载任何文件

### ISSUE THREAD

**Issue by DeepFal** [libsgh/PanIndex#97]
![](https://cc.deepfal.cn/2021/08/19/22998c6e558b7.png)
![](https://cc.deepfal.cn/2021/08/19/e7daf112320b2.png)
![](https://cc.deepfal.cn/2021/08/19/0000604bc46ab.png)
请问有什么解决办法嘛
可以上yun.deepfal.cn测试

**Comment by shelken** [comment]
加一，我也是这个问题。本来我是电脑端取的token，后来发现不行，然后用手机端抓包再取token发现可以用了。用了一会，又发现不行了。

**Comment by DeepFal** [comment]
问题已解决 是token的问题，正确的抓包姿势详见https://blog.deepfal.cn/index.php/archives/890/
