### ISSUE TITLE
天翼云视频加载失败

### ISSUE THREAD

**Issue by shelken** [libsgh/PanIndex#98]
资源可以下载，但是在线预览的时候直接控制台报错
`xxx.mp4:1 Refused to load media from 'http链接' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by shelken** [comment]
版本为最新版2.0.5。在docker部署

**Comment by shelken** [comment]
阿里云盘也测试了一下,都是这个问题
[tu](https://i.loli.net/2021/08/19/mRpdnQDCgzAfBxX.png)

**Comment by shelken** [comment]
<img src="https://i.loli.net/2021/08/19/mRpdnQDCgzAfBxX.png"></img>

**Comment by libsgh** [comment]
你有用nginx反代吗？看上去不是PanIndex的问题

**Comment by shelken** [comment]
> 你有用nginx反代吗？看上去不是PanIndex的问题

是的，用的nginx。请帮我看下我这些配置是否有什么问题？
server {
    listen 443 ssl;
    server_name xxx.com;
    include snippets/ssl-params.conf;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:5238;
    }
    client_max_body_size 1000m;
}

**Comment by libsgh** [comment]
把header去掉试试，你可以使用ip+端口 看看是不是正常的，如果是那就是代理有问题

**Comment by shelken** [comment]
我测试了一下，直接ip加端口没有问题。那应该是我的代理有点问题，请教下改怎么配置nginx呢？

**Comment by libsgh** [comment]
> 我测试了一下，直接ip加端口没有问题。那应该是我的代理有点问题，请教下改怎么配置nginx呢？

只能搜一下了，可以看看下面的链接，检查一下有没有哪设置content security policy

https://stackoverflow.com/questions/63320797/nginx-content-security-policy-not-being-acknowledged

**Comment by shelken** [comment]
解决了，原来引入另一个配置关于证书的配置里有加了这个csp的限制。注释后解决了
